<a href="https://colab.research.google.com/github/EgemenYapucu/DataScienceExercises/blob/main/Data_Mining_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Egemen Yapucu
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from pandas import unique

url = 'https://drive.google.com/file/d/13BRH0jKb3dBLJyURBix7ZlhUbgT5gADb/view?usp=sharing'
url1 = 'https://drive.google.com/uc?id=' + url.split('/')[-2]
df = pd.read_csv(url1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13551 entries, 0 to 13550
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              13551 non-null  int64
 1   self previous shot      13395 non-null  object
 2   player position         13551 non-null  object
 3   home game               13551 non-null  object
 4   location x              13541 non-null  float64
 5   opponent previous shot  13452 non-null  object
 6   home team               13551 non-null  object
 7   shot type               13551 non-null  object
 8   points                  13551 non-null  int64
 9   away team               13551 non-null  object
 10  location y              13541 non-null  float64
 11  time                    13551 non-null  object
 12  date                    13551 non-null  object
 13  shoot player            13551 non-null  object
 14  time from last shot     12911 non-null  float64
 15  quarter                 13551 non-null  int64
 16  current shot outcome    13551 non-null  object
 17  My_Team                 13551 non-null  object
 18  HomeAway                13551 non-null  object
 19  points_gained           13551 non-null  float64
 20  difference              13551 non-null  float64
dtypes: float64(5), int64(3), object(13)
memory usage: 2.2+ MB

In [ ]:
#Soru 1:
#Sadece Lebron james Atışları
dk = df.sort_values('shoot player')#Veri sort edildi oyunculara göre
dk = dk.reset_index()#indexi resetlendi
dk = dk.drop('index',axis = 1)#Gereksiz index kısmı düşürüldü
dfle = dk.iloc[8737:10033,:]#Lebrona ait olan atışlar çekildi
dfle = dfle.reset_index()#Bir daha resetlendi index
dfle = dfle.drop('index',axis = 1)#Bir daha düşürüldü
dfle.head()#İlk beş eleman yazdırıldı

,Unnamed: 0,self previous shot,player position,home game,location x,opponent previous shot,home team,shot type,points,away team,...,time,date,shoot player,time from last shot,quarter,current shot outcome,My_Team,HomeAway,points_gained,difference
0,1013,MISSED,SF,No,45.0,SCORED,PHI,Reverse Layup,2,CLE,...,9:42,2016-11-05,LeBron James,36.0,3,SCORED,CLE,PHI_CLE,2.0,-8.0
1,2314,BLOCKED,SF,No,851.0,SCORED,PHI,Fadeaway Jumper,2,CLE,...,1:05,2016-11-27,LeBron James,6.0,1,MISSED,CLE,PHI_CLE,0.0,-4.0
2,17,MISSED,SF,Yes,236.0,MISSED,CLE,Jump Shot,3,NYK,...,2:33,2016-10-25,LeBron James,6.0,1,MISSED,CLE,CLE_NYK,0.0,5.0
3,12239,MISSED,SF,Yes,888.0,MISSED,CLE,Cutting Dunk Shot,2,PHI,...,3:37,2017-03-31,LeBron James,4.0,3,SCORED,CLE,CLE_PHI,2.0,20.0
4,11906,MISSED,SF,No,58.0,MISSED,SAS,Driving Finger Roll Layup,2,CLE,...,7:47,2017-03-27,LeBron James,89.0,3,SCORED,CLE,SAS_CLE,2.0,-25.0

In [ ]:
#Soru 2:Verilerimizin içerisinde her sütün için kaç tane dolu veri var, percentile'ları kaç,
#ortalama değerleri kaç gibi değişkenleri gösteren kodu yazınız.
#Bütün kolonların isimlerini yazdırın.
df.count()#Her bir sütundaki dolu eleman sayısı

Unnamed: 0                13551
self previous shot        13395
player position           13551
home game                 13551
location x                13541
opponent previous shot    13452
home team                 13551
shot type                 13551
points                    13551
away team                 13551
location y                13541
time                      13551
date                      13551
shoot player              13551
time from last shot       12911
quarter                   13551
current shot outcome      13551
My_Team                   13551
HomeAway                  13551
points_gained             13551
difference                13551
dtype: int64

In [ ]:
df.mean()#Her bir sütunun ortalama değeri

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

Unnamed: 0             6775.000000
location x              466.775275
points                    2.362851
location y              246.795436
time from last shot      32.890636
quarter                   2.478489
points_gained             1.065604
difference                1.471847
dtype: float64

In [ ]:
df.median()#Her bir sütunun medyanı

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  """Entry point for launching an IPython kernel.

Unnamed: 0             6775.0
location x              313.0
points                    2.0
location y              250.0
time from last shot      31.0
quarter                   2.0
points_gained             0.0
difference                1.0
dtype: float64

In [ ]:
df.mode()#Her bir sütunun modu sadece ilk eleman dolu

,Unnamed: 0,self previous shot,player position,home game,location x,opponent previous shot,home team,shot type,points,away team,...,time,date,shoot player,time from last shot,quarter,current shot outcome,My_Team,HomeAway,points_gained,difference
0,0,MISSED,SF,Yes,888.0,SCORED,CLE,Jump Shot,2.0,CLE,...,12:00,2017-04-02,Kyrie Irving,28.0,1.0,MISSED,OPP,ATL_CLE,0.0,0.0
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13546,13546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13547,13547,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13548,13548,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13549,13549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13550,13550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#Soru 3:Sonrasında açılan notebook'tan verileri okutun.
#İlk 5 entry'sini yazdırın. Gözünüze çarpan şeyleri comment olarak ekleyin.
df.head()#İlk 5 entry yazdırıldı

,Unnamed: 0,self previous shot,player position,home game,location x,opponent previous shot,home team,shot type,points,away team,...,time,date,shoot player,time from last shot,quarter,current shot outcome,My_Team,HomeAway,points_gained,difference
0,0,NaN,PG,No,881.0,NaN,CLE,Driving Layup,2,NYK,...,0:20,2016-10-25,Derrick Rose,NaN,1,SCORED,OPP,CLE_NYK,2.0,0.0
1,1,NaN,PF,Yes,87.0,SCORED,CLE,Hook Shot,2,NYK,...,0:34,2016-10-25,Kevin Love,NaN,1,MISSED,CLE,CLE_NYK,0.0,-2.0
2,2,SCORED,SF,No,760.0,MISSED,CLE,Jump Shot,2,NYK,...,0:44,2016-10-25,Carmelo Anthony,24.0,1,MISSED,OPP,CLE_NYK,0.0,-2.0
3,3,MISSED,PF,No,890.0,MISSED,CLE,Tip Layup Shot,2,NYK,...,0:45,2016-10-25,Kristaps Porzingis,1.0,1,SCORED,OPP,CLE_NYK,2.0,-2.0
4,4,SCORED,SF,Yes,52.0,MISSED,CLE,Running Dunk,2,NYK,...,10:05,2016-10-25,Richard Jefferson,21.0,1,SCORED,CLE,CLE_NYK,2.0,-4.0

In [ ]:
#Verimiz 2016-10-25 tarihinden itibaren verileri bulunduruyor.
#Nan değere sahip veriler var.
#Verimizde 20 adet sütun bulunmaktadır.

In [ ]:
#Soru 4: Kaç sütun ve kaç satır içerdiğini yazdırın.
df.info()#Bütün sütun isimler ve eleman sayıları yazdırıldı

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13551 entries, 0 to 13550
Data columns (total 21 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              13551 non-null  int64
 1   self previous shot      13395 non-null  object
 2   player position         13551 non-null  object
 3   home game               13551 non-null  object
 4   location x              13541 non-null  float64
 5   opponent previous shot  13452 non-null  object
 6   home team               13551 non-null  object
 7   shot type               13551 non-null  object
 8   points                  13551 non-null  int64
 9   away team               13551 non-null  object
 10  location y              13541 non-null  float64
 11  time                    13551 non-null  object
 12  date                    13551 non-null  object
 13  shoot player            13551 non-null  object
 14  time from last shot     12911 non-null  float64
 15  quarter                 13551 non-null  int64
 16  current shot outcome    13551 non-null  object
 17  My_Team                 13551 non-null  object
 18  HomeAway                13551 non-null  object
 19  points_gained           13551 non-null  float64
 20  difference              13551 non-null  float64
dtypes: float64(5), int64(3), object(13)
memory usage: 2.2+ MB

In [ ]:
#Satır Sayısı
len(df)

13551

In [ ]:
#Sütun Sayısı
len(df.columns)

21

In [ ]:
#Satır ve Sütun Sayısı
df.shape

(13551, 21)

In [ ]:
#Soru 5:Değişken tiplerimiz neler? (Float,int,str) gibi, bunları yazdırın.
df.dtypes

Unnamed: 0                  int64
self previous shot         object
player position            object
home game                  object
location x                float64
opponent previous shot     object
home team                  object
shot type                  object
points                      int64
away team                  object
location y                float64
time                       object
date                       object
shoot player               object
time from last shot       float64
quarter                     int64
current shot outcome       object
My_Team                    object
HomeAway                   object
points_gained             float64
difference                float64
dtype: object

In [ ]:
#Soru 6: Cleveland takımında en yüksek yüzdeyle şut atan oyuncu kimdir?
#Bunu bulurken, bütün şutları değerlendirin, serbest atış, 2 sayılık atış ve 3 sayılık atış olması önemli değil.
#Bu değer kaçtır?
dc = dk.sort_values('My_Team')# Takımlara göre sıralanıp Cleveland'da oynayan oyuncular seçildi
dc = dc.reset_index()
dc = dc.iloc[0:6640,:]

dc = dc.drop('index',axis = 1)#Gereksiz sütunlar çıkarıldı
dc = dc.drop('self previous shot',axis = 1)
dc = dc.drop('player position',axis = 1)
dc = dc.drop('home game',axis = 1)
dc = dc.drop('location x',axis = 1)
dc = dc.drop('opponent previous shot',axis = 1)
dc = dc.drop('home team',axis = 1)
dc = dc.drop('shot type',axis = 1)
dc = dc.drop('away team',axis = 1)
dc = dc.drop('location y',axis = 1)
dc = dc.drop('time',axis = 1)
dc = dc.drop('date',axis = 1)
dc = dc.drop('time from last shot',axis = 1)
dc = dc.drop('quarter',axis = 1)
dc = dc.drop('HomeAway',axis = 1)
dc = dc.drop('points_gained',axis = 1)
dc = dc.drop('difference',axis = 1)
dc = dc.drop('points',axis = 1)

dc = dc.sort_values('shoot player')#Tekrar oyunculara göre sort edilip index resetlendi
dc = dc.reset_index()
dc = dc.drop('index',axis = 1)

In [ ]:
Frye = dc.iloc[0:500,:]#Herbir oyuncunun verileri ayrı dataframelere bölündü.
Frye = Frye.reset_index()
Frye = Frye.drop('index',axis = 1)
Curr = Frye['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Channing Frye'ın atış yüzdesi : %", Percentage['SCORED'])

Channing Frye'ın atış yüzdesi : % 45.4

In [ ]:
Andersen = dc.iloc[500:517,:]
Andersen = Andersen.reset_index()
Andersen = Andersen.drop('index',axis = 1)
Curr = Andersen['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Chris Andersen'in atış yüzdesi : %", Percentage['SCORED'])

Chris Andersen'in atış yüzdesi : % 52.94117647058824

In [ ]:
Liggins = dc.iloc[517:647,:]
Liggins = Liggins.reset_index()
Liggins = Liggins.drop('index',axis = 1)
Curr = Liggins['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("DeAndre Liggins'in atış yüzdesi : %", Percentage['SCORED'])

DeAndre Liggins'in atış yüzdesi : % 39.23076923076923

In [ ]:
Deron = dc.iloc[647:787,:]
Deron = Deron.reset_index()
Deron = Deron.drop('index',axis = 1)
Curr = Deron['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Deron Williams'ın atış yüzdesi : %", Percentage['SCORED'])

Deron Williams'ın atış yüzdesi : % 43.57142857142857

In [ ]:
Derrick = dc.iloc[787:882,:]
Derrick = Derrick.reset_index()
Derrick = Derrick.drop('index',axis = 1)
Curr = Derrick['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Derrick Williams'ın atış yüzdesi : %", Percentage['SCORED'])

Derrick Williams'ın atış yüzdesi : % 51.578947368421055

In [ ]:
Shumpert = dc.iloc[882:1335,:]
Shumpert = Shumpert.reset_index()
Shumpert = Shumpert.drop('index',axis = 1)
Curr = Shumpert['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100
print("Iman Shumpert'in atış yüzdesi : %", Percentage['SCORED'])

Iman Shumpert'in atış yüzdesi : % 40.397350993377486

In [ ]:
Smith = dc.iloc[1335:1670,:]
Smith = Smith.reset_index()
Smith = Smith.drop('index',axis = 1)
Curr = Smith['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("J.R. Smith'in atış yüzdesi : %", Percentage['SCORED'])

J.R. Smith'in atış yüzdesi : % 34.32835820895522

In [ ]:
Jones = dc.iloc[1670:1765,:]
Jones = Jones.reset_index()
Jones = Jones.drop('index',axis = 1)
Curr = Jones['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("James Jones'un atış yüzdesi : %", Percentage['SCORED'])

James Jones'un atış yüzdesi : % 48.421052631578945

In [ ]:
McRae = dc.iloc[1765:1906,:]
McRae = McRae.reset_index()
McRae = McRae.drop('index',axis = 1)
Curr = McRae['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Jordan McRae'nin atış yüzdesi : %", Percentage['SCORED'])

Jordan McRae'nin atış yüzdesi : % 39.00709219858156

In [ ]:
Felder = dc.iloc[1906:2056,:]
Felder = Felder.reset_index()
Felder = Felder.drop('index',axis = 1)
Curr = Felder['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Kay Felder'in atış yüzdesi : %", Percentage['SCORED'])

In [ ]:
Love = dc.iloc[2056:2899,:]
Love = Love.reset_index()
Love = Love.drop('index',axis = 1)
Curr = Love['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Kevin Love'ın atış yüzdesi : %", Percentage['SCORED'])

Kevin Love'ın atış yüzdesi : % 42.58600237247924

In [ ]:
Korver = dc.iloc[2899:3168,:]
Korver = Korver.reset_index()
Korver = Korver.drop('index',axis = 1)
Curr = Korver['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Kyle Korver'ın atış yüzdesi : %", Percentage['SCORED'])

Kyle Korver'ın atış yüzdesi : % 48.698884758364315

In [ ]:
Irving = dc.iloc[3168:4517,:]
Irving = Irving.reset_index()
Irving = Irving.drop('index',axis = 1)
Curr = Irving['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Kyrie Irving'in atış yüzdesi : %", Percentage['SCORED'])

Kyrie Irving'in atış yüzdesi : % 46.84951816160118

In [ ]:
Sanders = dc.iloc[4517:4520,:]
Sanders = Sanders.reset_index()
Sanders = Sanders.drop('index',axis = 1)
Curr = Sanders['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Larry Sanders'ın atış yüzdesi : %", Percentage['SCORED'])

Larry Sanders'ın atış yüzdesi : % 33.33333333333333

In [ ]:
LeBron = dc.iloc[4520:5815,:]
LeBron = LeBron.reset_index()
LeBron = LeBron.drop('index',axis = 1)
Curr = LeBron['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("LeBron James'in atış yüzdesi : %", Percentage['SCORED'])

LeBron James'in atış yüzdesi : % 54.749034749034756

In [ ]:
Dunleavy = dc.iloc[5815:5899,:]
Dunleavy = Dunleavy.reset_index()
Dunleavy = Dunleavy.drop('index',axis = 1)
Curr = Dunleavy['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Mike Dunleavy'in atış yüzdesi : %", Percentage['SCORED'])

Mike Dunleavy'in atış yüzdesi : % 38.095238095238095

In [ ]:
Thompson = dc.iloc[6220:6636,:]
Thompson = Thompson.reset_index()
Thompson = Thompson.drop('index',axis = 1)
Curr = Thompson['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Triston Thompson'ın atış yüzdesi : %", Percentage['SCORED'])

Triston Thompson'ın atış yüzdesi : % 60.817307692307686

In [ ]:
Tavares = dc.iloc[6636:6640,:]
Tavares = Tavares.reset_index()
Tavares = Tavares.drop('index',axis = 1)
Curr = Tavares['current shot outcome'].value_counts('SCORED')
Percentage = Curr*100 #SCORED değerlerinin yüzdesi hesaplanarak yazdırıldı.
print("Walter Tavares'in atış yüzdesi : %", Percentage['SCORED'])

Walter Tavares'in atış yüzdesi : % 75.0

Hesaplamalar göstermektedir ki en yüksek atış yüzdesine sahip oyuncu %75'lik başarı oranıyla Walter Tavares'tir.

In [ ]:
#Soru 7:Cleveland takımındaki her oyuncunun attığı toplam şut sayısını bulunuz.
print("Cleveland takımında atılan toplam şut sayısı = ",dc['current shot outcome'].count())

Cleveland takımında atılan toplam şut sayısı =  6640

In [ ]:
#Soru 8:Lebron James'in attığı şutların içerisinde maksimum x değerine
#sahip entry'nin indexini bulunuz.
dfx = dfle.sort_values('location x')
dfx = dfx.reset_index()
dfx = dfx.dropna()
Hx = dfx.iloc[:,5]
indx = dfx.iloc[:,1]
print("En büyük x değeri = ", Hx.iloc[-1])
print("En büyük x değeri indexi = ", indx.iloc[-1])

En büyük x değeri =  910.0
En büyük x değeri indexi =  12407

In [ ]:
#Soru 9: Bir fonksiyon tanımlayın. Buradaki amaç location y, ve location x verilerini
#fonksiyona verdiğinizde, şutun atıldığı noktanın potaya kuşbakışı uzaklığını(feet)
#buldurmaktır. Bu uzaklıkları 0-10,10-20,20-30, 30+ olacak şekilde,
#yakın, orta, uzak ve orta sahadan gibi isimlerle sınıflandırın.
#Bu sınıflandırmayı verinize yeni bir sütun(feature) olarak ekleyin.

def distance(x, y):
    dist = ((np.sqrt(np.square(x)+np.square(y)))/100)/0.3048#x ile y verisinin karesi alınıp toplandılar ardından karekök alınıp gerekli sabit ile çarpıldı.
    return dist

locx = df.iloc[:,4]
locy = df.iloc[:,10]

feature = distance(locx,locy)

df['Distance'] = feature#Elde edilen sayılar için Distance sütunu oluşturuldu

for i in range(len(feature)):
    if feature[i] <= 10:
        feature[i] = 'yakın'
    elif feature[i] <= 20:
        feature[i] = 'orta'
    elif feature[i] <= 30:
        feature[i] = 'uzak'
    else:
        feature[i] = 'orta sahadan'

df['Feature'] = feature#Elde edilen elemanlar için Feature sütunu oluşturuldu
df['Distance']

0        30.009859
1         8.344563
2        25.157946
3        30.126186
4         8.377649
           ...
13546    28.885257
13547     3.448785
13548    29.372387
13549    12.172093
13550    30.344009
Name: Distance, Length: 13551, dtype: float64

In [ ]:
df['Feature']

0        orta sahadan
1               yakın
2                uzak
3        orta sahadan
4               yakın
             ...
13546            uzak
13547           yakın
13548            uzak
13549            orta
13550    orta sahadan
Name: Feature, Length: 13551, dtype: object

In [ ]:
#Soru 10:Şut tiplerini bir liste haline getirin ve verilerin tümünü kullanarak
#her şuttan ne kadar kullanıldığını bulun. Listeyi alfabe sırasında sıralayın
#ve listenin sonuna kendi isimlendirdiğiniz bir şutu ekleyin.
#Sonra eklediğiniz bu şutu silin. Bank shot içeren indexleri bir liste haline getirin.

shott = df['shot type']#Şut tiplerinden bir liste oluşturuldu
shott = list(shott)
shott.sort()

alleyoopdunk = 0# Her atış için bir değişken tanımlandı.
alleyooplayup = 0
cuttingdunkshot = 0
cuttingfingerrolllayupshot = 0
cuttinglayupshot = 0
drivingbankhookshot = 0
drivingbankshot = 0
drivingdunk = 0
drivingfingerrolllayup = 0
drivingfloatingbankjumpshot = 0
drivingfloatingjumpshot = 0
drivinghookshot = 0
drivinglayup = 0
drivingreverselayup = 0
drivingreversedunkshot = 0
dunk = 0
fadeawaybankshot = 0
fadeawayjumper = 0
fingerrolllayup = 0
floatingjumpshot = 0
hookbankshot = 0
hookshot = 0
jumpbankshot = 0
jumpshot = 0
layup = 0
pullupbankshot = 0
pullupjumpshot = 0
putbackdunk = 0
putbacklayup = 0
reversedunk = 0
reverselayup = 0
runningalleyoopdunkshot = 0
runningalleyooplayupshot = 0
runningdunk = 0
runningfingerrolllayup = 0
runningjumpshot = 0
runninglayup = 0
runningpullupjumpshot = 0
runningreversedunkshot = 0
runningreverselayup = 0
stepbackbankjumpshot = 0
stepbackjumpshot = 0
tipdunkshot = 0
tiplayupshot = 0
turnaroundbankhookshot = 0
turnaroundbankshot = 0
turnaroundfadeaway = 0
turnaroundfadeawaybankjumpshot = 0
turnaroundfadeawayshot = 0
turnaroundhookshot = 0
turnaroundjumpshot = 0


for i in range(len(shott)):#O değişkenlerin sayıları hesap edildi.
    if shott[i] == 'Alley Oop Dunk':
        alleyoopdunk=alleyoopdunk+1
    elif shott[i] == 'Alley Oop Layup':
        alleyooplayup=alleyooplayup+1
    elif shott[i] == 'Cutting Dunk Shot':
        cuttingdunkshot = cuttingdunkshot+1
    elif shott[i] == 'Cutting Finger Roll Layup Shot':
        cuttingfingerrolllayupshot = cuttingfingerrolllayupshot+1
    elif shott[i] == 'Cutting Layup Shot':
        cuttinglayupshot = cuttinglayupshot+1
    elif shott[i] == 'Driving Bank Hook Shot':
        drivingbankhookshot = drivingbankhookshot+1
    elif shott[i] == 'Driving Bank Shot':
        drivingbankshot = drivingbankshot+1
    elif shott[i] == 'Driving Dunk':
        drivingdunk = drivingdunk+1
    elif shott[i] == 'Driving Finger Roll Layup':
        drivingfingerrolllayup = drivingfingerrolllayup+1
    elif shott[i] == 'Driving Floating Bank Jump Shot':
        drivingfloatingbankjumpshot = drivingfloatingbankjumpshot+1
    elif shott[i] == 'Driving Floating Jump Shot':
        drivingfloatingjumpshot = drivingfloatingjumpshot+1
    elif shott[i] == 'Driving Hook Shot':
        drivinghookshot = drivinghookshot+1
    elif shott[i] == 'Driving Layup':
        drivinglayup = drivinglayup+1
    elif shott[i] == 'Driving Reverse Dunk Shot':
        drivingreversedunkshot = drivingreversedunkshot+1
    elif shott[i] == 'Driving Reverse Layup':
        drivingreverselayup = drivingreverselayup+1
    elif shott[i] == 'Dunk':
        dunk = dunk+1
    elif shott[i] == 'Fadeaway Bank Shot':
        fadeawaybankshot = fadeawaybankshot+1
    elif shott[i] == 'Fadeaway Jumper':
        fadeawayjumper = fadeawayjumper+1
    elif shott[i] == 'Finger Roll Layup':
        fingerrolllayup = fingerrolllayup+1
    elif shott[i] == 'Floating Jump Shot':
        floatingjumpshot = floatingjumpshot+1
    elif shott[i] == 'Hook Bank Shot':
        hookbankshot = hookbankshot+1
    elif shott[i] == 'Hook Shot':
        hookshot = hookshot+1
    elif shott[i] == 'Jump Bank Shot':
        jumpbankshot = jumpbankshot+1
    elif shott[i] == 'Jump Shot':
        jumpshot = jumpshot+1
    elif shott[i] == 'Layup':
        layup = layup+1
    elif shott[i] == 'Pullup Bank Shot':
        pullupbankshot = pullupbankshot+1
    elif shott[i] == 'Pullup Jump Shot':
        pullupjumpshot = pullupjumpshot+1
    elif shott[i] == 'Putback Dunk':
        putbackdunk = putbackdunk+1
    elif shott[i] == 'Putback Layup':
        putbacklayup = putbacklayup+1
    elif shott[i] == 'Reverse Dunk':
        reversedunk = reversedunk+1
    elif shott[i] == 'Reverse Layup':
        reverselayup = reverselayup+1
    elif shott[i] == 'Running Alley Oop Dunk Shot':
        runningalleyoopdunkshot = runningalleyoopdunkshot+1
    elif shott[i] == 'Running Alley Oop Layup Shot':
        runningalleyooplayupshot = runningalleyooplayupshot+1
    elif shott[i] == 'Running Dunk':
        runningdunk = runningdunk+1
    elif shott[i] == 'Running Finger Roll Layup':
        runningfingerrolllayup = runningfingerrolllayup+1
    elif shott[i] == 'Running Jump Shot':
        runningjumpshot = runningjumpshot+1
    elif shott[i] == 'Running Layup':
        runninglayup = runninglayup+1
    elif shott[i] == 'Running Pull-Up Jump Shot':
        runningpullupjumpshot = runningpullupjumpshot+1
    elif shott[i] == 'Running Reverse Dunk Shot':
        runningreversedunkshot = runningreversedunkshot+1
    elif shott[i] == 'Running Reverse Layup':
        runningreverselayup = runningreverselayup+1
    elif shott[i] == 'Step Back Bank Jump Shot':
        stepbackbankjumpshot = stepbackbankjumpshot+1
    elif shott[i] == 'Step Back Jump Shot':
        stepbackjumpshot = stepbackjumpshot+1
    elif shott[i] == 'Tip Dunk Shot':
        tipdunkshot = tipdunkshot+1
    elif shott[i] == 'Tip Layup Shot':
        tiplayupshot = tiplayupshot+1
    elif shott[i] == 'Turnaround Bank Hook Shot':
        turnaroundbankhookshot = turnaroundbankhookshot+1
    elif shott[i] == 'Turnaround Bank Shot':
        turnaroundbankshot = turnaroundbankshot+1
    elif shott[i] == 'Turnaround Fadeaway':
        turnaroundfadeaway = turnaroundfadeaway+1
    elif shott[i] == 'Turnaround Fadeaway Bank Jump Shot':
        turnaroundfadeawaybankjumpshot = turnaroundfadeawaybankjumpshot+1
    elif shott[i] == 'Turnaround Fadeaway Shot':
        turnaroundfadeawayshot = turnaroundfadeawayshot+1
    elif shott[i] == 'Turnaround Hook Shot':
        turnaroundhookshot = turnaroundhookshot+1
    elif shott[i] == 'Turnaround Jump Shot':
        turnaroundjumpshot = turnaroundjumpshot+1
shottype = ['Alley Oop Dunk','Alley Oop Layup','Cutting Dunk Shot','Cutting Finger Roll Layup Shot'
             ,'Cutting Layup Shot','Driving Bank Hook Shot','Driving Bank Shot','Driving Dunk',
             'Driving Finger Roll Layup','Driving Floating Bank Jump Shot' , 'Driving Floating Jump Shot' ,
             'Driving Hook Shot', 'Driving Layup', 'Driving Reverse Dunk Shot', 'Driving Reverse Layup'
             , 'Dunk' , 'Fadeaway Bank Shot' , 'Fadeaway Jumper' , 'Finger Roll Layup' , 'Floating Jump Shot'
             , 'Hook Bank Shot' , 'Hook Shot' , 'Jump Bank Shot' , 'Jump Shot' , 'Layup' , 'Pullup Bank Shot'
             , 'Pullup Jump Shot' , 'Putback Dunk' ,'Putback Layup' , 'Reverse Dunk' , 'Reverse Layup' ,
             'Running Alley Oop Dunk Shot', 'Running Alley Oop Layup Shot' ,'Running Dunk' , 'Running Finger Roll Layup'
             , 'Running Jump Shot' , 'Running Layup' , 'Running Pull-Up Jump Shot' , 'Running Reverse Dunk Shot'
             , 'Running Reverse Layup' , 'Step Back Bank Jump Shot' ,'Step Back Jump Shot' , 'Tip Dunk Shot' ,
             'Tip Layup Shot' , 'Turnaround Bank Hook Shot' , 'Turnaround Bank Shot' , 'Turnaround Fadeaway' ,
             'Turnaround Fadeaway Bank Jump Shot' , 'Turnaround Fadeaway Shot' , 'Turnaround Hook Shot' , 'Turnaround Jump Shot' ]#Her bir atışın bulunduğu bir liste oluşturuldu
values = [alleyoopdunk, alleyooplayup, cuttingdunkshot, cuttingfingerrolllayupshot,
          cuttinglayupshot, drivingbankhookshot, drivingbankshot, drivingdunk, drivingfingerrolllayup,
          drivingfloatingbankjumpshot, drivingfloatingjumpshot, drivinghookshot, drivinglayup,
          drivingreverselayup, drivingreversedunkshot, dunk, fadeawaybankshot, fadeawayjumper, fingerrolllayup,
          floatingjumpshot, hookbankshot, hookshot, jumpbankshot, jumpshot, layup, pullupbankshot,
          pullupjumpshot, putbackdunk, putbacklayup, reversedunk, reverselayup, runningalleyoopdunkshot,
          runningalleyooplayupshot, runningdunk, runningfingerrolllayup, runningjumpshot,
          runninglayup, runningpullupjumpshot, runningreversedunkshot, runningreverselayup,
          stepbackbankjumpshot, stepbackjumpshot, tipdunkshot, tiplayupshot, turnaroundbankhookshot,
          turnaroundbankshot, turnaroundfadeaway, turnaroundfadeawaybankjumpshot, turnaroundfadeawayshot,
          turnaroundhookshot, turnaroundjumpshot]#Hesaplanan depişkenlerin tutulduğu liste
shottypes = {}#Dictionary
for i in shottype:# İki liste dictionary içinde birleştirildi
    for j in values:
        shottypes[i] = j
        values.remove(j)
        break
values = [alleyoopdunk, alleyooplayup, cuttingdunkshot, cuttingfingerrolllayupshot,
          cuttinglayupshot, drivingbankhookshot, drivingbankshot, drivingdunk, drivingfingerrolllayup,
          drivingfloatingbankjumpshot, drivingfloatingjumpshot, drivinghookshot, drivinglayup,
          drivingreverselayup, drivingreversedunkshot, dunk, fadeawaybankshot, fadeawayjumper, fingerrolllayup,
          floatingjumpshot, hookbankshot, hookshot, jumpbankshot, jumpshot, layup, pullupbankshot,
          pullupjumpshot, putbackdunk, putbacklayup, reversedunk, reverselayup, runningalleyoopdunkshot,
          runningalleyooplayupshot, runningdunk, runningfingerrolllayup, runningjumpshot,
          runninglayup, runningpullupjumpshot, runningreversedunkshot, runningreverselayup,
          stepbackbankjumpshot, stepbackjumpshot, tipdunkshot, tiplayupshot, turnaroundbankhookshot,
          turnaroundbankshot, turnaroundfadeaway, turnaroundfadeawaybankjumpshot, turnaroundfadeawayshot,
          turnaroundhookshot, turnaroundjumpshot]
print(shottype)

['Alley Oop Dunk', 'Alley Oop Layup', 'Cutting Dunk Shot', 'Cutting Finger Roll Layup Shot', 'Cutting Layup Shot', 'Driving Bank Hook Shot', 'Driving Bank Shot', 'Driving Dunk', 'Driving Finger Roll Layup', 'Driving Floating Bank Jump Shot', 'Driving Floating Jump Shot', 'Driving Hook Shot', 'Driving Layup', 'Driving Reverse Dunk Shot', 'Driving Reverse Layup', 'Dunk', 'Fadeaway Bank Shot', 'Fadeaway Jumper', 'Finger Roll Layup', 'Floating Jump Shot', 'Hook Bank Shot', 'Hook Shot', 'Jump Bank Shot', 'Jump Shot', 'Layup', 'Pullup Bank Shot', 'Pullup Jump Shot', 'Putback Dunk', 'Putback Layup', 'Reverse Dunk', 'Reverse Layup', 'Running Alley Oop Dunk Shot', 'Running Alley Oop Layup Shot', 'Running Dunk', 'Running Finger Roll Layup', 'Running Jump Shot', 'Running Layup', 'Running Pull-Up Jump Shot', 'Running Reverse Dunk Shot', 'Running Reverse Layup', 'Step Back Bank Jump Shot', 'Step Back Jump Shot', 'Tip Dunk Shot', 'Tip Layup Shot', 'Turnaround Bank Hook Shot', 'Turnaround Bank Shot', 'Turnaround Fadeaway', 'Turnaround Fadeaway Bank Jump Shot', 'Turnaround Fadeaway Shot', 'Turnaround Hook Shot', 'Turnaround Jump Shot']

In [ ]:
print(values)

[89, 56, 188, 19, 279, 3, 98, 108, 134, 42, 207, 73, 1018, 105, 3, 147, 13, 157, 25, 229, 5, 192, 145, 6656, 760, 32, 696, 37, 154, 6, 138, 6, 4, 105, 40, 79, 256, 26, 1, 23, 5, 317, 37, 275, 6, 36, 77, 2, 83, 99, 259]

In [ ]:
print(shottypes)

{'Alley Oop Dunk': 89, 'Alley Oop Layup': 56, 'Cutting Dunk Shot': 188, 'Cutting Finger Roll Layup Shot': 19, 'Cutting Layup Shot': 279, 'Driving Bank Hook Shot': 3, 'Driving Bank Shot': 98, 'Driving Dunk': 108, 'Driving Finger Roll Layup': 134, 'Driving Floating Bank Jump Shot': 42, 'Driving Floating Jump Shot': 207, 'Driving Hook Shot': 73, 'Driving Layup': 1018, 'Driving Reverse Dunk Shot': 105, 'Driving Reverse Layup': 3, 'Dunk': 147, 'Fadeaway Bank Shot': 13, 'Fadeaway Jumper': 157, 'Finger Roll Layup': 25, 'Floating Jump Shot': 229, 'Hook Bank Shot': 5, 'Hook Shot': 192, 'Jump Bank Shot': 145, 'Jump Shot': 6656, 'Layup': 760, 'Pullup Bank Shot': 32, 'Pullup Jump Shot': 696, 'Putback Dunk': 37, 'Putback Layup': 154, 'Reverse Dunk': 6, 'Reverse Layup': 138, 'Running Alley Oop Dunk Shot': 6, 'Running Alley Oop Layup Shot': 4, 'Running Dunk': 105, 'Running Finger Roll Layup': 40, 'Running Jump Shot': 79, 'Running Layup': 256, 'Running Pull-Up Jump Shot': 26, 'Running Reverse Dunk Shot': 1, 'Running Reverse Layup': 23, 'Step Back Bank Jump Shot': 5, 'Step Back Jump Shot': 317, 'Tip Dunk Shot': 37, 'Tip Layup Shot': 275, 'Turnaround Bank Hook Shot': 6, 'Turnaround Bank Shot': 36, 'Turnaround Fadeaway': 77, 'Turnaround Fadeaway Bank Jump Shot': 2, 'Turnaround Fadeaway Shot': 83, 'Turnaround Hook Shot': 99, 'Turnaround Jump Shot': 259}

In [ ]:
shottype.append('egemen')
print(shottype)

['Alley Oop Dunk', 'Alley Oop Layup', 'Cutting Dunk Shot', 'Cutting Finger Roll Layup Shot', 'Cutting Layup Shot', 'Driving Bank Hook Shot', 'Driving Bank Shot', 'Driving Dunk', 'Driving Finger Roll Layup', 'Driving Floating Bank Jump Shot', 'Driving Floating Jump Shot', 'Driving Hook Shot', 'Driving Layup', 'Driving Reverse Dunk Shot', 'Driving Reverse Layup', 'Dunk', 'Fadeaway Bank Shot', 'Fadeaway Jumper', 'Finger Roll Layup', 'Floating Jump Shot', 'Hook Bank Shot', 'Hook Shot', 'Jump Bank Shot', 'Jump Shot', 'Layup', 'Pullup Bank Shot', 'Pullup Jump Shot', 'Putback Dunk', 'Putback Layup', 'Reverse Dunk', 'Reverse Layup', 'Running Alley Oop Dunk Shot', 'Running Alley Oop Layup Shot', 'Running Dunk', 'Running Finger Roll Layup', 'Running Jump Shot', 'Running Layup', 'Running Pull-Up Jump Shot', 'Running Reverse Dunk Shot', 'Running Reverse Layup', 'Step Back Bank Jump Shot', 'Step Back Jump Shot', 'Tip Dunk Shot', 'Tip Layup Shot', 'Turnaround Bank Hook Shot', 'Turnaround Bank Shot', 'Turnaround Fadeaway', 'Turnaround Fadeaway Bank Jump Shot', 'Turnaround Fadeaway Shot', 'Turnaround Hook Shot', 'Turnaround Jump Shot', 'egemen']

In [ ]:
shottype.remove('egemen')
print(shottype)

['Alley Oop Dunk', 'Alley Oop Layup', 'Cutting Dunk Shot', 'Cutting Finger Roll Layup Shot', 'Cutting Layup Shot', 'Driving Bank Hook Shot', 'Driving Bank Shot', 'Driving Dunk', 'Driving Finger Roll Layup', 'Driving Floating Bank Jump Shot', 'Driving Floating Jump Shot', 'Driving Hook Shot', 'Driving Layup', 'Driving Reverse Dunk Shot', 'Driving Reverse Layup', 'Dunk', 'Fadeaway Bank Shot', 'Fadeaway Jumper', 'Finger Roll Layup', 'Floating Jump Shot', 'Hook Bank Shot', 'Hook Shot', 'Jump Bank Shot', 'Jump Shot', 'Layup', 'Pullup Bank Shot', 'Pullup Jump Shot', 'Putback Dunk', 'Putback Layup', 'Reverse Dunk', 'Reverse Layup', 'Running Alley Oop Dunk Shot', 'Running Alley Oop Layup Shot', 'Running Dunk', 'Running Finger Roll Layup', 'Running Jump Shot', 'Running Layup', 'Running Pull-Up Jump Shot', 'Running Reverse Dunk Shot', 'Running Reverse Layup', 'Step Back Bank Jump Shot', 'Step Back Jump Shot', 'Tip Dunk Shot', 'Tip Layup Shot', 'Turnaround Bank Hook Shot', 'Turnaround Bank Shot', 'Turnaround Fadeaway', 'Turnaround Fadeaway Bank Jump Shot', 'Turnaround Fadeaway Shot', 'Turnaround Hook Shot', 'Turnaround Jump Shot']

In [ ]:
bankshot = []
count = 0
for i in df['shot type']:
    count = count + 1
    if "Bank Shot" in i:
        bankshot.append(df['Unnamed: 0'].iloc[count-1])
print(bankshot)

[109, 125, 131, 135, 169, 183, 228, 313, 320, 397, 436, 441, 461, 514, 537, 544, 567, 568, 579, 599, 619, 650, 670, 677, 758, 857, 866, 895, 902, 908, 977, 1078, 1114, 1128, 1147, 1170, 1189, 1193, 1200, 1208, 1218, 1239, 1367, 1423, 1428, 1449, 1508, 1544, 1600, 1635, 1685, 1714, 1836, 1869, 1906, 1934, 1945, 1947, 2011, 2047, 2069, 2104, 2127, 2150, 2215, 2653, 2666, 2672, 2707, 2708, 2709, 2760, 3041, 3124, 3161, 3266, 3326, 3365, 3370, 3394, 3408, 3430, 3524, 3574, 3587, 3657, 3661, 3666, 3709, 3710, 3726, 3727, 3760, 3762, 3778, 3783, 3910, 3972, 4007, 4016, 4185, 4192, 4380, 4435, 4470, 4494, 4508, 4526, 4543, 4580, 4591, 4700, 4712, 4724, 4747, 4769, 4871, 4877, 4939, 4946, 4968, 5112, 5114, 5124, 5148, 5231, 5242, 5248, 5250, 5277, 5304, 5306, 5346, 5365, 5370, 5386, 5387, 5393, 5413, 5420, 5430, 5511, 5533, 5588, 5625, 5681, 5694, 5720, 5726, 5741, 5772, 5800, 5825, 5842, 5913, 5923, 5936, 5958, 6032, 6153, 6173, 6516, 6600, 6602, 6665, 6705, 6716, 6729, 6803, 6822, 6829, 6890, 6916, 7110, 7255, 7289, 7360, 7433, 7461, 7580, 7653, 7656, 7824, 7834, 7880, 7887, 7905, 7909, 7952, 7975, 7984, 8018, 8172, 8173, 8239, 8242, 8382, 8419, 8424, 8467, 8509, 8568, 8581, 8690, 8712, 8792, 8808, 8827, 8844, 8911, 8950, 8971, 9036, 9037, 9038, 9072, 9151, 9176, 9200, 9221, 9232, 9265, 9349, 9429, 9471, 9518, 9575, 9593, 9595, 9606, 9662, 9676, 9683, 9704, 9773, 9986, 10005, 10021, 10059, 10076, 10222, 10275, 10295, 10311, 10315, 10341, 10380, 10415, 10445, 10468, 10578, 10788, 10850, 10853, 10856, 10869, 10893, 10913, 10917, 10948, 11023, 11057, 11114, 11159, 11211, 11250, 11276, 11320, 11354, 11408, 11429, 11430, 11433, 11542, 11555, 11560, 11564, 11629, 11634, 11739, 11751, 11778, 11784, 11796, 11849, 11864, 11913, 11937, 11965, 11994, 12150, 12152, 12153, 12167, 12187, 12220, 12228, 12253, 12263, 12273, 12287, 12291, 12344, 12441, 12527, 12557, 12561, 12619, 12621, 12644, 12705, 12747, 12833, 12924, 12967, 13034, 13043, 13045, 13060, 13160, 13197, 13236, 13277, 13308, 13330, 13348, 13367, 13368, 13416]

In [ ]:
#Soru 11:Boş bir seri yaratın. Şut tiplerinden 'a' harfi içerenleri listede tutmak
#için bir kod yazın.
st = []
for i in shottype:
    if "a" in i:
        st.append(i)
st

['Alley Oop Layup',
 'Cutting Finger Roll Layup Shot',
 'Cutting Layup Shot',
 'Driving Bank Hook Shot',
 'Driving Bank Shot',
 'Driving Finger Roll Layup',
 'Driving Floating Bank Jump Shot',
 'Driving Floating Jump Shot',
 'Driving Layup',
 'Driving Reverse Layup',
 'Fadeaway Bank Shot',
 'Fadeaway Jumper',
 'Finger Roll Layup',
 'Floating Jump Shot',
 'Hook Bank Shot',
 'Jump Bank Shot',
 'Layup',
 'Pullup Bank Shot',
 'Putback Dunk',
 'Putback Layup',
 'Reverse Layup',
 'Running Alley Oop Layup Shot',
 'Running Finger Roll Layup',
 'Running Layup',
 'Running Reverse Layup',
 'Step Back Bank Jump Shot',
 'Step Back Jump Shot',
 'Tip Layup Shot',
 'Turnaround Bank Hook Shot',
 'Turnaround Bank Shot',
 'Turnaround Fadeaway',
 'Turnaround Fadeaway Bank Jump Shot',
 'Turnaround Fadeaway Shot',
 'Turnaround Hook Shot',
 'Turnaround Jump Shot']

In [ ]:
#Soru 12:Derste işlediğimiz, 'List comprehension' kullanarak, atılan tüm şutlardan
#kaç tanesinin y değerinin 250'den büyük olduğunu veren fonksiyonu yazın.
#Örnek: def......
#Return .....
#Örnekteki gibi 2 satırda yapmanız gereklidir.
def maxy(): return len([i for i in df['location y'] if i > 250])
maxy()

6295

In [ ]:
#Soru 13: Bir dictionary oluşturun. O dictionary'e verimizin quarter bilgisini
#gönderceğiz. O gönderdiğimiz sayıya göre ilk çeyrek, ikinci çeyrek,
#üçüncü çeyrek ve son çeyrek olarak değiştirsin.
dict = {}
j = 0
for i in df['quarter']:
    dict[j] = i
    j = j+1
for i in dict:
    if dict[i] == 1:
        dict[i] = 'ilk çeyrek'
    elif dict[i] == 2:
        dict[i] = 'ikinci çeyrek'
    elif dict[i] == 3:
        dict[i] = 'üçüncü çeyrek'
    elif dict[i] == 4:
        dict[i] = 'dördüncü çeyrek'
dict

{0: 'ilk çeyrek',
 1: 'ilk çeyrek',
 2: 'ilk çeyrek',
 3: 'ilk çeyrek',
 4: 'ilk çeyrek',
 5: 'ilk çeyrek',
 6: 'ilk çeyrek',
 7: 'ilk çeyrek',
 8: 'ilk çeyrek',
 9: 'ilk çeyrek',
 10: 'ilk çeyrek',
 11: 'ilk çeyrek',
 12: 'ilk çeyrek',
 13: 'ilk çeyrek',
 14: 'ilk çeyrek',
 15: 'ilk çeyrek',
 16: 'ilk çeyrek',
 17: 'ilk çeyrek',
 18: 'ilk çeyrek',
 19: 'ilk çeyrek',
 20: 'ilk çeyrek',
 21: 'ilk çeyrek',
 22: 'ilk çeyrek',
 23: 'ilk çeyrek',
 24: 'ilk çeyrek',
 25: 'ilk çeyrek',
 26: 'ilk çeyrek',
 27: 'ilk çeyrek',
 28: 'ilk çeyrek',
 29: 'ilk çeyrek',
 30: 'ilk çeyrek',
 31: 'ilk çeyrek',
 32: 'ilk çeyrek',
 33: 'ilk çeyrek',
 34: 'ilk çeyrek',
 35: 'ilk çeyrek',
 36: 'ilk çeyrek',
 37: 'ilk çeyrek',
 38: 'ilk çeyrek',
 39: 'ilk çeyrek',
 40: 'ilk çeyrek',
 41: 'ilk çeyrek',
 42: 'ilk çeyrek',
 43: 'ilk çeyrek',
 44: 'ilk çeyrek',
 45: 'ilk çeyrek',
 46: 'ilk çeyrek',
 47: 'ilk çeyrek',
 48: 'ilk çeyrek',
 49: 'ilk çeyrek',
 50: 'ilk çeyrek',
 51: 'ikinci çeyrek',
 52: 'ikinci çeyrek',
 53: 'ikinci çeyrek',
 54: 'ikinci çeyrek',
 55: 'ikinci çeyrek',
 56: 'ikinci çeyrek',
 57: 'ikinci çeyrek',
 58: 'ikinci çeyrek',
 59: 'ikinci çeyrek',
 60: 'ikinci çeyrek',
 61: 'ikinci çeyrek',
 62: 'ikinci çeyrek',
 63: 'ikinci çeyrek',
 64: 'ikinci çeyrek',
 65: 'ikinci çeyrek',
 66: 'ikinci çeyrek',
 67: 'ikinci çeyrek',
 68: 'ikinci çeyrek',
 69: 'ikinci çeyrek',
 70: 'ikinci çeyrek',
 71: 'ikinci çeyrek',
 72: 'ikinci çeyrek',
 73: 'ikinci çeyrek',
 74: 'ikinci çeyrek',
 75: 'ikinci çeyrek',
 76: 'ikinci çeyrek',
 77: 'ikinci çeyrek',
 78: 'ikinci çeyrek',
 79: 'ikinci çeyrek',
 80: 'ikinci çeyrek',
 81: 'ikinci çeyrek',
 82: 'ikinci çeyrek',
 83: 'ikinci çeyrek',
 84: 'ikinci çeyrek',
 85: 'ikinci çeyrek',
 86: 'ikinci çeyrek',
 87: 'ikinci çeyrek',
 88: 'ikinci çeyrek',
 89: 'ikinci çeyrek',
 90: 'ikinci çeyrek',
 91: 'ikinci çeyrek',
 92: 'ikinci çeyrek',
 93: 'ikinci çeyrek',
 94: 'ikinci çeyrek',
 95: 'ikinci çeyrek',
 96: 'ikinci çeyrek',
 97: 'üçüncü çeyrek',
 98: 'üçüncü çeyrek',
 99: 'üçüncü çeyrek',
 100: 'üçüncü çeyrek',
 101: 'üçüncü çeyrek',
 102: 'üçüncü çeyrek',
 103: 'üçüncü çeyrek',
 104: 'üçüncü çeyrek',
 105: 'üçüncü çeyrek',
 106: 'üçüncü çeyrek',
 107: 'üçüncü çeyrek',
 108: 'üçüncü çeyrek',
 109: 'üçüncü çeyrek',
 110: 'üçüncü çeyrek',
 111: 'üçüncü çeyrek',
 112: 'üçüncü çeyrek',
 113: 'üçüncü çeyrek',
 114: 'üçüncü çeyrek',
 115: 'üçüncü çeyrek',
 116: 'üçüncü çeyrek',
 117: 'üçüncü çeyrek',
 118: 'üçüncü çeyrek',
 119: 'üçüncü çeyrek',
 120: 'üçüncü çeyrek',
 121: 'üçüncü çeyrek',
 122: 'üçüncü çeyrek',
 123: 'üçüncü çeyrek',
 124: 'üçüncü çeyrek',
 125: 'üçüncü çeyrek',
 126: 'üçüncü çeyrek',
 127: 'üçüncü çeyrek',
 128: 'üçüncü çeyrek',
 129: 'üçüncü çeyrek',
 130: 'üçüncü çeyrek',
 131: 'üçüncü çeyrek',
 132: 'üçüncü çeyrek',
 133: 'üçüncü çeyrek',
 134: 'üçüncü çeyrek',
 135: 'üçüncü çeyrek',
 136: 'üçüncü çeyrek',
 137: 'dördüncü çeyrek',
 138: 'dördüncü çeyrek',
 139: 'dördüncü çeyrek',
 140: 'dördüncü çeyrek',
 141: 'dördüncü çeyrek',
 142: 'dördüncü çeyrek',
 143: 'dördüncü çeyrek',
 144: 'dördüncü çeyrek',
 145: 'dördüncü çeyrek',
 146: 'dördüncü çeyrek',
 147: 'dördüncü çeyrek',
 148: 'dördüncü çeyrek',
 149: 'dördüncü çeyrek',
 150: 'dördüncü çeyrek',
 151: 'dördüncü çeyrek',
 152: 'dördüncü çeyrek',
 153: 'dördüncü çeyrek',
 154: 'dördüncü çeyrek',
 155: 'dördüncü çeyrek',
 156: 'dördüncü çeyrek',
 157: 'dördüncü çeyrek',
 158: 'dördüncü çeyrek',
 159: 'dördüncü çeyrek',
 160: 'dördüncü çeyrek',
 161: 'dördüncü çeyrek',
 162: 'dördüncü çeyrek',
 163: 'dördüncü çeyrek',
 164: 'dördüncü çeyrek',
 165: 'dördüncü çeyrek',
 166: 'dördüncü çeyrek',
 167: 'dördüncü çeyrek',
 168: 'dördüncü çeyrek',
 169: 'dördüncü çeyrek',
 170: 'dördüncü çeyrek',
 171: 'dördüncü çeyrek',
 172: 'dördüncü çeyrek',
 173: 'dördüncü çeyrek',
 174: 'dördüncü çeyrek',
 175: 'dördüncü çeyrek',
 176: 'dördüncü çeyrek',
 177: 'dördüncü çeyrek',
 178: 'dördüncü çeyrek',
 179: 'dördüncü çeyrek',
 180: 'dördüncü çeyrek',
 181: 'ilk çeyrek',
 182: 'ilk çeyrek',
 183: 'ilk çeyrek',
 184: 'ilk çeyrek',
 185: 'ilk çeyrek',
 186: 'ilk çeyrek',
 187: 'ilk çeyrek',
 188: 'ilk çeyrek',
 189: 'ilk çeyrek',
 190: 'ilk çeyrek',
 191: 'ilk çeyrek',
 192: 'ilk çeyrek',
 193: 'ilk çeyrek',
 194: 'ilk çeyrek',
 195: 'ilk çeyrek',
 196: 'ilk çeyrek',
 197: 'ilk çeyrek',
 198: 'ilk çeyrek',
 199: 'ilk çeyrek',
 200: 'ilk çeyrek',
 201: 'ilk çeyrek',
 202: 'ilk çeyrek',
 203: 'ilk çeyrek',
 204: 'ilk çeyrek',
 205: 'ilk çeyrek',
 206: 'ilk çeyrek',
 207: 'ilk çeyrek',
 208: 'ilk çeyrek',
 209: 'ilk çeyrek',
 210: 'ilk çeyrek',
 211: 'ilk çeyrek',
 212: 'ilk çeyrek',
 213: 'ilk çeyrek',
 214: 'ilk çeyrek',
 215: 'ilk çeyrek',
 216: 'ilk çeyrek',
 217: 'ilk çeyrek',
 218: 'ilk çeyrek',
 219: 'ilk çeyrek',
 220: 'ilk çeyrek',
 221: 'ilk çeyrek',
 222: 'ilk çeyrek',
 223: 'ilk çeyrek',
 224: 'ilk çeyrek',
 225: 'ilk çeyrek',
 226: 'ilk çeyrek',
 227: 'ilk çeyrek',
 228: 'ilk çeyrek',
 229: 'ikinci çeyrek',
 230: 'ikinci çeyrek',
 231: 'ikinci çeyrek',
 232: 'ikinci çeyrek',
 233: 'ikinci çeyrek',
 234: 'ikinci çeyrek',
 235: 'ikinci çeyrek',
 236: 'ikinci çeyrek',
 237: 'ikinci çeyrek',
 238: 'ikinci çeyrek',
 239: 'ikinci çeyrek',
 240: 'ikinci çeyrek',
 241: 'ikinci çeyrek',
 242: 'ikinci çeyrek',
 243: 'ikinci çeyrek',
 244: 'ikinci çeyrek',
 245: 'ikinci çeyrek',
 246: 'ikinci çeyrek',
 247: 'ikinci çeyrek',
 248: 'ikinci çeyrek',
 249: 'ikinci çeyrek',
 250: 'ikinci çeyrek',
 251: 'ikinci çeyrek',
 252: 'ikinci çeyrek',
 253: 'ikinci çeyrek',
 254: 'ikinci çeyrek',
 255: 'ikinci çeyrek',
 256: 'ikinci çeyrek',
 257: 'ikinci çeyrek',
 258: 'ikinci çeyrek',
 259: 'ikinci çeyrek',
 260: 'ikinci çeyrek',
 261: 'ikinci çeyrek',
 262: 'ikinci çeyrek',
 263: 'ikinci çeyrek',
 264: 'ikinci çeyrek',
 265: 'ikinci çeyrek',
 266: 'ikinci çeyrek',
 267: 'üçüncü çeyrek',
 268: 'üçüncü çeyrek',
 269: 'üçüncü çeyrek',
 270: 'üçüncü çeyrek',
 271: 'üçüncü çeyrek',
 272: 'üçüncü çeyrek',
 273: 'üçüncü çeyrek',
 274: 'üçüncü çeyrek',
 275: 'üçüncü çeyrek',
 276: 'üçüncü çeyrek',
 277: 'üçüncü çeyrek',
 278: 'üçüncü çeyrek',
 279: 'üçüncü çeyrek',
 280: 'üçüncü çeyrek',
 281: 'üçüncü çeyrek',
 282: 'üçüncü çeyrek',
 283: 'üçüncü çeyrek',
 284: 'üçüncü çeyrek',
 285: 'üçüncü çeyrek',
 286: 'üçüncü çeyrek',
 287: 'üçüncü çeyrek',
 288: 'üçüncü çeyrek',
 289: 'üçüncü çeyrek',
 290: 'üçüncü çeyrek',
 291: 'üçüncü çeyrek',
 292: 'üçüncü çeyrek',
 293: 'üçüncü çeyrek',
 294: 'üçüncü çeyrek',
 295: 'üçüncü çeyrek',
 296: 'üçüncü çeyrek',
 297: 'üçüncü çeyrek',
 298: 'üçüncü çeyrek',
 299: 'üçüncü çeyrek',
 300: 'üçüncü çeyrek',
 301: 'üçüncü çeyrek',
 302: 'üçüncü çeyrek',
 303: 'üçüncü çeyrek',
 304: 'üçüncü çeyrek',
 305: 'üçüncü çeyrek',
 306: 'üçüncü çeyrek',
 307: 'üçüncü çeyrek',
 308: 'dördüncü çeyrek',
 309: 'dördüncü çeyrek',
 310: 'dördüncü çeyrek',
 311: 'dördüncü çeyrek',
 312: 'dördüncü çeyrek',
 313: 'dördüncü çeyrek',
 314: 'dördüncü çeyrek',
 315: 'dördüncü çeyrek',
 316: 'dördüncü çeyrek',
 317: 'dördüncü çeyrek',
 318: 'dördüncü çeyrek',
 319: 'dördüncü çeyrek',
 320: 'dördüncü çeyrek',
 321: 'dördüncü çeyrek',
 322: 'dördüncü çeyrek',
 323: 'dördüncü çeyrek',
 324: 'dördüncü çeyrek',
 325: 'dördüncü çeyrek',
 326: 'dördüncü çeyrek',
 327: 'dördüncü çeyrek',
 328: 'dördüncü çeyrek',
 329: 'dördüncü çeyrek',
 330: 'dördüncü çeyrek',
 331: 'dördüncü çeyrek',
 332: 'dördüncü çeyrek',
 333: 'dördüncü çeyrek',
 334: 'dördüncü çeyrek',
 335: 'dördüncü çeyrek',
 336: 'dördüncü çeyrek',
 337: 'dördüncü çeyrek',
 338: 'dördüncü çeyrek',
 339: 'dördüncü çeyrek',
 340: 'dördüncü çeyrek',
 341: 'dördüncü çeyrek',
 342: 'dördüncü çeyrek',
 343: 'dördüncü çeyrek',
 344: 'dördüncü çeyrek',
 345: 'dördüncü çeyrek',
 346: 'dördüncü çeyrek',
 347: 'dördüncü çeyrek',
 348: 'dördüncü çeyrek',
 349: 'dördüncü çeyrek',
 350: 'ilk çeyrek',
 351: 'ilk çeyrek',
 352: 'ilk çeyrek',
 353: 'ilk çeyrek',
 354: 'ilk çeyrek',
 355: 'ilk çeyrek',
 356: 'ilk çeyrek',
 357: 'ilk çeyrek',
 358: 'ilk çeyrek',
 359: 'ilk çeyrek',
 360: 'ilk çeyrek',
 361: 'ilk çeyrek',
 362: 'ilk çeyrek',
 363: 'ilk çeyrek',
 364: 'ilk çeyrek',
 365: 'ilk çeyrek',
 366: 'ilk çeyrek',
 367: 'ilk çeyrek',
 368: 'ilk çeyrek',
 369: 'ilk çeyrek',
 370: 'ilk çeyrek',
 371: 'ilk çeyrek',
 372: 'ilk çeyrek',
 373: 'ilk çeyrek',
 374: 'ilk çeyrek',
 375: 'ilk çeyrek',
 376: 'ilk çeyrek',
 377: 'ilk çeyrek',
 378: 'ilk çeyrek',
 379: 'ilk çeyrek',
 380: 'ilk çeyrek',
 381: 'ilk çeyrek',
 382: 'ilk çeyrek',
 383: 'ilk çeyrek',
 384: 'ilk çeyrek',
 385: 'ilk çeyrek',
 386: 'ilk çeyrek',
 387: 'ilk çeyrek',
 388: 'ilk çeyrek',
 389: 'ilk çeyrek',
 390: 'ilk çeyrek',
 391: 'ilk çeyrek',
 392: 'ilk çeyrek',
 393: 'ilk çeyrek',
 394: 'ilk çeyrek',
 395: 'ikinci çeyrek',
 396: 'ikinci çeyrek',
 397: 'ikinci çeyrek',
 398: 'ikinci çeyrek',
 399: 'ikinci çeyrek',
 400: 'ikinci çeyrek',
 401: 'ikinci çeyrek',
 402: 'ikinci çeyrek',
 403: 'ikinci çeyrek',
 404: 'ikinci çeyrek',
 405: 'ikinci çeyrek',
 406: 'ikinci çeyrek',
 407: 'ikinci çeyrek',
 408: 'ikinci çeyrek',
 409: 'ikinci çeyrek',
 410: 'ikinci çeyrek',
 411: 'ikinci çeyrek',
 412: 'ikinci çeyrek',
 413: 'ikinci çeyrek',
 414: 'ikinci çeyrek',
 415: 'ikinci çeyrek',
 416: 'ikinci çeyrek',
 417: 'ikinci çeyrek',
 418: 'ikinci çeyrek',
 419: 'ikinci çeyrek',
 420: 'ikinci çeyrek',
 421: 'ikinci çeyrek',
 422: 'ikinci çeyrek',
 423: 'ikinci çeyrek',
 424: 'ikinci çeyrek',
 425: 'ikinci çeyrek',
 426: 'ikinci çeyrek',
 427: 'ikinci çeyrek',
 428: 'ikinci çeyrek',
 429: 'ikinci çeyrek',
 430: 'ikinci çeyrek',
 431: 'ikinci çeyrek',
 432: 'ikinci çeyrek',
 433: 'ikinci çeyrek',
 434: 'ikinci çeyrek',
 435: 'ikinci çeyrek',
 436: 'ikinci çeyrek',
 437: 'ikinci çeyrek',
 438: 'ikinci çeyrek',
 439: 'ikinci çeyrek',
 440: 'üçüncü çeyrek',
 441: 'üçüncü çeyrek',
 442: 'üçüncü çeyrek',
 443: 'üçüncü çeyrek',
 444: 'üçüncü çeyrek',
 445: 'üçüncü çeyrek',
 446: 'üçüncü çeyrek',
 447: 'üçüncü çeyrek',
 448: 'üçüncü çeyrek',
 449: 'üçüncü çeyrek',
 450: 'üçüncü çeyrek',
 451: 'üçüncü çeyrek',
 452: 'üçüncü çeyrek',
 453: 'üçüncü çeyrek',
 454: 'üçüncü çeyrek',
 455: 'üçüncü çeyrek',
 456: 'üçüncü çeyrek',
 457: 'üçüncü çeyrek',
 458: 'üçüncü çeyrek',
 459: 'üçüncü çeyrek',
 460: 'üçüncü çeyrek',
 461: 'üçüncü çeyrek',
 462: 'üçüncü çeyrek',
 463: 'üçüncü çeyrek',
 464: 'üçüncü çeyrek',
 465: 'üçüncü çeyrek',
 466: 'üçüncü çeyrek',
 467: 'üçüncü çeyrek',
 468: 'üçüncü çeyrek',
 469: 'üçüncü çeyrek',
 470: 'üçüncü çeyrek',
 471: 'üçüncü çeyrek',
 472: 'üçüncü çeyrek',
 473: 'üçüncü çeyrek',
 474: 'üçüncü çeyrek',
 475: 'üçüncü çeyrek',
 476: 'üçüncü çeyrek',
 477: 'üçüncü çeyrek',
 478: 'üçüncü çeyrek',
 479: 'dördüncü çeyrek',
 480: 'dördüncü çeyrek',
 481: 'dördüncü çeyrek',
 482: 'dördüncü çeyrek',
 483: 'dördüncü çeyrek',
 484: 'dördüncü çeyrek',
 485: 'dördüncü çeyrek',
 486: 'dördüncü çeyrek',
 487: 'dördüncü çeyrek',
 488: 'dördüncü çeyrek',
 489: 'dördüncü çeyrek',
 490: 'dördüncü çeyrek',
 491: 'dördüncü çeyrek',
 492: 'dördüncü çeyrek',
 493: 'dördüncü çeyrek',
 494: 'dördüncü çeyrek',
 495: 'dördüncü çeyrek',
 496: 'dördüncü çeyrek',
 497: 'dördüncü çeyrek',
 498: 'dördüncü çeyrek',
 499: 'dördüncü çeyrek',
 500: 'dördüncü çeyrek',
 501: 'dördüncü çeyrek',
 502: 'dördüncü çeyrek',
 503: 'dördüncü çeyrek',
 504: 'dördüncü çeyrek',
 505: 'dördüncü çeyrek',
 506: 'dördüncü çeyrek',
 507: 'dördüncü çeyrek',
 508: 'dördüncü çeyrek',
 509: 'dördüncü çeyrek',
 510: 'dördüncü çeyrek',
 511: 'dördüncü çeyrek',
 512: 'dördüncü çeyrek',
 513: 'dördüncü çeyrek',
 514: 'dördüncü çeyrek',
 515: 'dördüncü çeyrek',
 516: 'dördüncü çeyrek',
 517: 'dördüncü çeyrek',
 518: 'dördüncü çeyrek',
 519: 'dördüncü çeyrek',
 520: 'dördüncü çeyrek',
 521: 'dördüncü çeyrek',
 522: 'ilk çeyrek',
 523: 'ilk çeyrek',
 524: 'ilk çeyrek',
 525: 'ilk çeyrek',
 526: 'ilk çeyrek',
 527: 'ilk çeyrek',
 528: 'ilk çeyrek',
 529: 'ilk çeyrek',
 530: 'ilk çeyrek',
 531: 'ilk çeyrek',
 532: 'ilk çeyrek',
 533: 'ilk çeyrek',
 534: 'ilk çeyrek',
 535: 'ilk çeyrek',
 536: 'ilk çeyrek',
 537: 'ilk çeyrek',
 538: 'ilk çeyrek',
 539: 'ilk çeyrek',
 540: 'ilk çeyrek',
 541: 'ilk çeyrek',
 542: 'ilk çeyrek',
 543: 'ilk çeyrek',
 544: 'ilk çeyrek',
 545: 'ilk çeyrek',
 546: 'ilk çeyrek',
 547: 'ilk çeyrek',
 548: 'ilk çeyrek',
 549: 'ilk çeyrek',
 550: 'ilk çeyrek',
 551: 'ilk çeyrek',
 552: 'ilk çeyrek',
 553: 'ilk çeyrek',
 554: 'ilk çeyrek',
 555: 'ilk çeyrek',
 556: 'ilk çeyrek',
 557: 'ilk çeyrek',
 558: 'ilk çeyrek',
 559: 'ilk çeyrek',
 560: 'ilk çeyrek',
 561: 'ilk çeyrek',
 562: 'ilk çeyrek',
 563: 'ilk çeyrek',
 564: 'ilk çeyrek',
 565: 'ilk çeyrek',
 566: 'ilk çeyrek',
 567: 'ikinci çeyrek',
 568: 'ikinci çeyrek',
 569: 'ikinci çeyrek',
 570: 'ikinci çeyrek',
 571: 'ikinci çeyrek',
 572: 'ikinci çeyrek',
 573: 'ikinci çeyrek',
 574: 'ikinci çeyrek',
 575: 'ikinci çeyrek',
 576: 'ikinci çeyrek',
 577: 'ikinci çeyrek',
 578: 'ikinci çeyrek',
 579: 'ikinci çeyrek',
 580: 'ikinci çeyrek',
 581: 'ikinci çeyrek',
 582: 'ikinci çeyrek',
 583: 'ikinci çeyrek',
 584: 'ikinci çeyrek',
 585: 'ikinci çeyrek',
 586: 'ikinci çeyrek',
 587: 'ikinci çeyrek',
 588: 'ikinci çeyrek',
 589: 'ikinci çeyrek',
 590: 'ikinci çeyrek',
 591: 'ikinci çeyrek',
 592: 'ikinci çeyrek',
 593: 'ikinci çeyrek',
 594: 'ikinci çeyrek',
 595: 'ikinci çeyrek',
 596: 'ikinci çeyrek',
 597: 'ikinci çeyrek',
 598: 'ikinci çeyrek',
 599: 'ikinci çeyrek',
 600: 'ikinci çeyrek',
 601: 'ikinci çeyrek',
 602: 'ikinci çeyrek',
 603: 'ikinci çeyrek',
 604: 'ikinci çeyrek',
 605: 'ikinci çeyrek',
 606: 'ikinci çeyrek',
 607: 'ikinci çeyrek',
 608: 'ikinci çeyrek',
 609: 'ikinci çeyrek',
 610: 'ikinci çeyrek',
 611: 'ikinci çeyrek',
 612: 'ikinci çeyrek',
 613: 'üçüncü çeyrek',
 614: 'üçüncü çeyrek',
 615: 'üçüncü çeyrek',
 616: 'üçüncü çeyrek',
 617: 'üçüncü çeyrek',
 618: 'üçüncü çeyrek',
 619: 'üçüncü çeyrek',
 620: 'üçüncü çeyrek',
 621: 'üçüncü çeyrek',
 622: 'üçüncü çeyrek',
 623: 'üçüncü çeyrek',
 624: 'üçüncü çeyrek',
 625: 'üçüncü çeyrek',
 626: 'üçüncü çeyrek',
 627: 'üçüncü çeyrek',
 628: 'üçüncü çeyrek',
 629: 'üçüncü çeyrek',
 630: 'üçüncü çeyrek',
 631: 'üçüncü çeyrek',
 632: 'üçüncü çeyrek',
 633: 'üçüncü çeyrek',
 634: 'üçüncü çeyrek',
 635: 'üçüncü çeyrek',
 636: 'üçüncü çeyrek',
 637: 'üçüncü çeyrek',
 638: 'üçüncü çeyrek',
 639: 'üçüncü çeyrek',
 640: 'üçüncü çeyrek',
 641: 'üçüncü çeyrek',
 642: 'üçüncü çeyrek',
 643: 'üçüncü çeyrek',
 644: 'üçüncü çeyrek',
 645: 'üçüncü çeyrek',
 646: 'üçüncü çeyrek',
 647: 'üçüncü çeyrek',
 648: 'üçüncü çeyrek',
 649: 'üçüncü çeyrek',
 650: 'üçüncü çeyrek',
 651: 'üçüncü çeyrek',
 652: 'üçüncü çeyrek',
 653: 'üçüncü çeyrek',
 654: 'üçüncü çeyrek',
 655: 'üçüncü çeyrek',
 656: 'üçüncü çeyrek',
 657: 'üçüncü çeyrek',
 658: 'üçüncü çeyrek',
 659: 'dördüncü çeyrek',
 660: 'dördüncü çeyrek',
 661: 'dördüncü çeyrek',
 662: 'dördüncü çeyrek',
 663: 'dördüncü çeyrek',
 664: 'dördüncü çeyrek',
 665: 'dördüncü çeyrek',
 666: 'dördüncü çeyrek',
 667: 'dördüncü çeyrek',
 668: 'dördüncü çeyrek',
 669: 'dördüncü çeyrek',
 670: 'dördüncü çeyrek',
 671: 'dördüncü çeyrek',
 672: 'dördüncü çeyrek',
 673: 'dördüncü çeyrek',
 674: 'dördüncü çeyrek',
 675: 'dördüncü çeyrek',
 676: 'dördüncü çeyrek',
 677: 'dördüncü çeyrek',
 678: 'dördüncü çeyrek',
 679: 'dördüncü çeyrek',
 680: 'dördüncü çeyrek',
 681: 'dördüncü çeyrek',
 682: 'dördüncü çeyrek',
 683: 'dördüncü çeyrek',
 684: 'dördüncü çeyrek',
 685: 'dördüncü çeyrek',
 686: 'dördüncü çeyrek',
 687: 'dördüncü çeyrek',
 688: 'dördüncü çeyrek',
 689: 'dördüncü çeyrek',
 690: 'dördüncü çeyrek',
 691: 'dördüncü çeyrek',
 692: 'dördüncü çeyrek',
 693: 'dördüncü çeyrek',
 694: 'dördüncü çeyrek',
 695: 'ilk çeyrek',
 696: 'ilk çeyrek',
 697: 'ilk çeyrek',
 698: 'ilk çeyrek',
 699: 'ilk çeyrek',
 700: 'ilk çeyrek',
 701: 'ilk çeyrek',
 702: 'ilk çeyrek',
 703: 'ilk çeyrek',
 704: 'ilk çeyrek',
 705: 'ilk çeyrek',
 706: 'ilk çeyrek',
 707: 'ilk çeyrek',
 708: 'ilk çeyrek',
 709: 'ilk çeyrek',
 710: 'ilk çeyrek',
 711: 'ilk çeyrek',
 712: 'ilk çeyrek',
 713: 'ilk çeyrek',
 714: 'ilk çeyrek',
 715: 'ilk çeyrek',
 716: 'ilk çeyrek',
 717: 'ilk çeyrek',
 718: 'ilk çeyrek',
 719: 'ilk çeyrek',
 720: 'ilk çeyrek',
 721: 'ilk çeyrek',
 722: 'ilk çeyrek',
 723: 'ilk çeyrek',
 724: 'ilk çeyrek',
 725: 'ilk çeyrek',
 726: 'ilk çeyrek',
 727: 'ilk çeyrek',
 728: 'ilk çeyrek',
 729: 'ilk çeyrek',
 730: 'ilk çeyrek',
 731: 'ilk çeyrek',
 732: 'ilk çeyrek',
 733: 'ilk çeyrek',
 734: 'ilk çeyrek',
 735: 'ilk çeyrek',
 736: 'ilk çeyrek',
 737: 'ilk çeyrek',
 738: 'ilk çeyrek',
 739: 'ilk çeyrek',
 740: 'ilk çeyrek',
 741: 'ilk çeyrek',
 742: 'ilk çeyrek',
 743: 'ilk çeyrek',
 744: 'ilk çeyrek',
 745: 'ikinci çeyrek',
 746: 'ikinci çeyrek',
 747: 'ikinci çeyrek',
 748: 'ikinci çeyrek',
 749: 'ikinci çeyrek',
 750: 'ikinci çeyrek',
 751: 'ikinci çeyrek',
 752: 'ikinci çeyrek',
 753: 'ikinci çeyrek',
 754: 'ikinci çeyrek',
 755: 'ikinci çeyrek',
 756: 'ikinci çeyrek',
 757: 'ikinci çeyrek',
 758: 'ikinci çeyrek',
 759: 'ikinci çeyrek',
 760: 'ikinci çeyrek',
 761: 'ikinci çeyrek',
 762: 'ikinci çeyrek',
 763: 'ikinci çeyrek',
 764: 'ikinci çeyrek',
 765: 'ikinci çeyrek',
 766: 'ikinci çeyrek',
 767: 'ikinci çeyrek',
 768: 'ikinci çeyrek',
 769: 'ikinci çeyrek',
 770: 'ikinci çeyrek',
 771: 'ikinci çeyrek',
 772: 'ikinci çeyrek',
 773: 'ikinci çeyrek',
 774: 'ikinci çeyrek',
 775: 'ikinci çeyrek',
 776: 'ikinci çeyrek',
 777: 'ikinci çeyrek',
 778: 'ikinci çeyrek',
 779: 'ikinci çeyrek',
 780: 'ikinci çeyrek',
 781: 'ikinci çeyrek',
 782: 'ikinci çeyrek',
 783: 'ikinci çeyrek',
 784: 'ikinci çeyrek',
 785: 'ikinci çeyrek',
 786: 'ikinci çeyrek',
 787: 'ikinci çeyrek',
 788: 'üçüncü çeyrek',
 789: 'üçüncü çeyrek',
 790: 'üçüncü çeyrek',
 791: 'üçüncü çeyrek',
 792: 'üçüncü çeyrek',
 793: 'üçüncü çeyrek',
 794: 'üçüncü çeyrek',
 795: 'üçüncü çeyrek',
 796: 'üçüncü çeyrek',
 797: 'üçüncü çeyrek',
 798: 'üçüncü çeyrek',
 799: 'üçüncü çeyrek',
 800: 'üçüncü çeyrek',
 801: 'üçüncü çeyrek',
 802: 'üçüncü çeyrek',
 803: 'üçüncü çeyrek',
 804: 'üçüncü çeyrek',
 805: 'üçüncü çeyrek',
 806: 'üçüncü çeyrek',
 807: 'üçüncü çeyrek',
 808: 'üçüncü çeyrek',
 809: 'üçüncü çeyrek',
 810: 'üçüncü çeyrek',
 811: 'üçüncü çeyrek',
 812: 'üçüncü çeyrek',
 813: 'üçüncü çeyrek',
 814: 'üçüncü çeyrek',
 815: 'üçüncü çeyrek',
 816: 'üçüncü çeyrek',
 817: 'üçüncü çeyrek',
 818: 'üçüncü çeyrek',
 819: 'üçüncü çeyrek',
 820: 'üçüncü çeyrek',
 821: 'üçüncü çeyrek',
 822: 'üçüncü çeyrek',
 823: 'üçüncü çeyrek',
 824: 'üçüncü çeyrek',
 825: 'üçüncü çeyrek',
 826: 'üçüncü çeyrek',
 827: 'üçüncü çeyrek',
 828: 'üçüncü çeyrek',
 829: 'üçüncü çeyrek',
 830: 'üçüncü çeyrek',
 831: 'üçüncü çeyrek',
 832: 'dördüncü çeyrek',
 833: 'dördüncü çeyrek',
 834: 'dördüncü çeyrek',
 835: 'dördüncü çeyrek',
 836: 'dördüncü çeyrek',
 837: 'dördüncü çeyrek',
 838: 'dördüncü çeyrek',
 839: 'dördüncü çeyrek',
 840: 'dördüncü çeyrek',
 841: 'dördüncü çeyrek',
 842: 'dördüncü çeyrek',
 843: 'dördüncü çeyrek',
 844: 'dördüncü çeyrek',
 845: 'dördüncü çeyrek',
 846: 'dördüncü çeyrek',
 847: 'dördüncü çeyrek',
 848: 'dördüncü çeyrek',
 849: 'dördüncü çeyrek',
 850: 'dördüncü çeyrek',
 851: 'dördüncü çeyrek',
 852: 'dördüncü çeyrek',
 853: 'dördüncü çeyrek',
 854: 'dördüncü çeyrek',
 855: 'dördüncü çeyrek',
 856: 'dördüncü çeyrek',
 857: 'dördüncü çeyrek',
 858: 'dördüncü çeyrek',
 859: 'dördüncü çeyrek',
 860: 'dördüncü çeyrek',
 861: 'dördüncü çeyrek',
 862: 'dördüncü çeyrek',
 863: 'dördüncü çeyrek',
 864: 'dördüncü çeyrek',
 865: 'dördüncü çeyrek',
 866: 'dördüncü çeyrek',
 867: 'dördüncü çeyrek',
 868: 'dördüncü çeyrek',
 869: 'dördüncü çeyrek',
 870: 'dördüncü çeyrek',
 871: 'dördüncü çeyrek',
 872: 'dördüncü çeyrek',
 873: 'dördüncü çeyrek',
 874: 'dördüncü çeyrek',
 875: 'ilk çeyrek',
 876: 'ilk çeyrek',
 877: 'ilk çeyrek',
 878: 'ilk çeyrek',
 879: 'ilk çeyrek',
 880: 'ilk çeyrek',
 881: 'ilk çeyrek',
 882: 'ilk çeyrek',
 883: 'ilk çeyrek',
 884: 'ilk çeyrek',
 885: 'ilk çeyrek',
 886: 'ilk çeyrek',
 887: 'ilk çeyrek',
 888: 'ilk çeyrek',

In [ ]:
#Soru 14:Bugüne kadar kullandığımız bütün module/library'leri yazın. Module'un veya library'nin hangi fonksiyonları
#içerdiğini yazdırın. O fonksiyonlardan görmediğimiz bir tanesini seçin,
#ve fonksiyonun hangi değişkenleri aldığını, o değişkenlerin anlamlarını yazdırın.

Python dilinin Pandas ve Numpy kütüphanelerini kullandık. Pandas bize yüksek performansa sahip veri yapılarını ve veri analizi için gerekli araçları sağlar. Numpy ise bize gerekli matematiksel işlemleri ve matris işlemleri için gerekli fonksiyonları sağlar.

In [ ]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_distributor_init',
 '_financial_names',
 '_globals',
 '_mat',
 '_pytesttester',
 '_version',
 'abs',
 'absolute',
 'add',
 'add_docstring',
 'add_newdoc',
 'add_newdoc_ufunc',
 'alen',
 'all',
 'allclose',
 'alltrue',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'asanyarray',
 'asarray',
 'asarray_chkfinite',
 'ascontiguousarray',
 'asfarray',
 'asfortranarray',
 'asmatrix',
 'asscalar',
 'atleast_1d',
 'atleast_2d',
 'atleast_3d',
 'average',
 'bartlett',
 'base_repr',
 'binary_repr',
 'bincount',
 'bitwise_and',
 'bitwise_not',
 'bitwise_or',
 'bitwise_xor',
 'blackman',
 'block',
 'bmat',
 'bool8',
 'bool_',
 'broadcast',
 'broadcast_arrays',
 'broadcast_shapes',
 'broadcast_to',
 'busday_count',
 'busday_offset',
 'busdaycalendar',
 'byte',
 'byte_bounds',
 'bytes0',
 'bytes_',
 'c_',
 'can_cast',
 'cast',
 'cbrt',
 'cdouble',
 'ceil',
 'cfloat',
 'char',
 'character',
 'chararray',
 'choose',
 'clip',
 'clongdouble',
 'clongfloat',
 'column_stack',
 'common_type',
 'compare_chararrays',
 'compat',
 'complex128',
 'complex256',
 'complex64',
 'complex_',
 'complexfloating',
 'compress',
 'concatenate',
 'conj',
 'conjugate',
 'convolve',
 'copy',
 'copysign',
 'copyto',
 'core',
 'corrcoef',
 'correlate',
 'cos',
 'cosh',
 'count_nonzero',
 'cov',
 'cross',
 'csingle',
 'ctypeslib',
 'cumprod',
 'cumproduct',
 'cumsum',
 'datetime64',
 'datetime_as_string',
 'datetime_data',
 'deg2rad',
 'degrees',
 'delete',
 'deprecate',
 'deprecate_with_doc',
 'diag',
 'diag_indices',
 'diag_indices_from',
 'diagflat',
 'diagonal',
 'diff',
 'digitize',
 'disp',
 'divide',
 'divmod',
 'dot',
 'double',
 'dsplit',
 'dstack',
 'dtype',
 'dual',
 'e',
 'ediff1d',
 'einsum',
 'einsum_path',
 'emath',
 'empty',
 'empty_like',
 'equal',
 'errstate',
 'euler_gamma',
 'exp',
 'exp2',
 'expand_dims',
 'expm1',
 'extract',
 'eye',
 'fabs',
 'fastCopyAndTranspose',
 'fft',
 'fill_diagonal',
 'find_common_type',
 'finfo',
 'fix',
 'flatiter',
 'flatnonzero',
 'flexible',
 'flip',
 'fliplr',
 'flipud',
 'float128',
 'float16',
 'float32',
 'float64',
 'float_',
 'float_power',
 'floating',
 'floor',
 'floor_divide',
 'fmax',
 'fmin',
 'fmod',
 'format_float_positional',
 'format_float_scientific',
 'format_parser',
 'frexp',
 'frombuffer',
 'fromfile',
 'fromfunction',
 'fromiter',
 'frompyfunc',
 'fromregex',
 'fromstring',
 'full',
 'full_like',
 'gcd',
 'generic',
 'genfromtxt',
 'geomspace',
 'get_array_wrap',
 'get_include',
 'get_printoptions',
 'getbufsize',
 'geterr',
 'geterrcall',
 'geterrobj',
 'gradient',
 'greater',
 'greater_equal',
 'half',
 'hamming',
 'hanning',
 'heaviside',
 'histogram',
 'histogram2d',
 'histogram_bin_edges',
 'histogramdd',
 'hsplit',
 'hstack',
 'hypot',
 'i0',
 'identity',
 'iinfo',
 'imag',
 'in1d',
 'index_exp',
 'indices',
 'inexact',
 'inf',
 'info',
 'infty',
 'inner',
 'insert',
 'int0',
 'int16',
 'int32',
 'int64',
 'int8',
 'int_',
 'intc',
 'integer',
 'interp',
 'intersect1d',
 'intp',
 'invert',
 'is_busday',
 'isclose',
 'iscomplex',
 'iscomplexobj',
 'isfinite',
 'isfortran',
 'isin',
 'isinf',
 'isnan',
 'isnat',
 'isneginf',
 'isposinf',
 'isreal',
 'isrealobj',
 'isscalar',
 'issctype',
 'issubclass_',
 'issubdtype',
 'issubsctype',
 'iterable',
 'ix_',
 'kaiser',
 'kernel_version',
 'kron',
 'lcm',
 'ldexp',
 'left_shift',
 'less',
 'less_equal',
 'lexsort',
 'lib',
 'linalg',
 'linspace',
 'little_endian',
 'load',
 'loads',
 'loadtxt',
 'log',
 'log10',
 'log1p',
 'log2',
 'logaddexp',
 'logaddexp2',
 'logical_and',
 'logical_not',
 'logical_or',
 'logical_xor',
 'logspace',
 'longcomplex',
 'longdouble',
 'longfloat',
 'longlong',
 'lookfor',
 'ma',
 'mafromtxt',
 'mask_indices',
 'mat',
 'math',
 'matmul',
 'matrix',
 'matrixlib',
 'max',
 'maximum',
 'maximum_sctype',
 'may_share_memory',
 'mean',
 'median',
 'memmap',
 'meshgrid',
 'mgrid',
 'min',
 'min_scalar_type',
 'minimum',
 'mintypecode',
 'mod',
 'modf',
 'moveaxis',
 'msort',
 'multiply',
 'nan',
 'nan_to_num',
 'nanargmax',
 'nanargmin',
 'nancumprod',
 'nancumsum',
 'nanmax',
 'nanmean',
 'nanmedian',
 'nanmin',
 'nanpercentile',
 'nanprod',
 'nanquantile',
 'nanstd',
 'nansum',
 'nanvar',
 'nbytes',
 'ndarray',
 'ndenumerate',
 'ndfromtxt',
 'ndim',
 'ndindex',
 'nditer',
 'negative',
 'nested_iters',
 'newaxis',
 'nextafter',
 'nonzero',
 'not_equal',
 'numarray',
 'number',
 'obj2sctype',
 'object0',
 'object_',
 'ogrid',
 'oldnumeric',
 'ones',
 'ones_like',
 'os',
 'outer',
 'packbits',
 'pad',
 'partition',
 'percentile',
 'pi',
 'piecewise',
 'place',
 'poly',
 'poly1d',
 'polyadd',
 'polyder',
 'polydiv',
 'polyfit',
 'polyint',
 'polymul',
 'polynomial',
 'polysub',
 'polyval',
 'positive',
 'power',
 'printoptions',
 'prod',
 'product',
 'promote_types',
 'ptp',
 'put',
 'put_along_axis',
 'putmask',
 'quantile',
 'r_',
 'rad2deg',
 'radians',
 'random',
 'ravel',
 'ravel_multi_index',
 'real',
 'real_if_close',
 'rec',
 'recarray',
 'recfromcsv',
 'recfromtxt',
 'reciprocal',
 'record',
 'remainder',
 'repeat',
 'require',
 'reshape',
 'resize',
 'result_type',
 'right_shift',
 'rint',
 'roll',
 'rollaxis',
 'roots',
 'rot90',
 'round',
 'round_',
 'row_stack',
 's_',
 'safe_eval',
 'save',
 'savetxt',
 'savez',
 'savez_compressed',
 'sctype2char',
 'sctypeDict',
 'sctypes',
 'searchsorted',
 'select',
 'set_numeric_ops',
 'set_printoptions',
 'set_string_function',
 'setbufsize',
 'setdiff1d',
 'seterr',
 'seterrcall',
 'seterrobj',
 'setxor1d',
 'shape',
 'shares_memory',
 'short',
 'show_config',
 'sign',
 'signbit',
 'signedinteger',
 'sin',
 'sinc',
 'single',
 'singlecomplex',
 'sinh',
 'size',
 'sometrue',
 'sort',
 'sort_complex',
 'source',
 'spacing',
 'split',
 'sqrt',
 'square',
 'squeeze',
 'stack',
 'std',
 'str0',
 'str_',
 'string_',
 'subtract',
 'sum',
 'swapaxes',
 'sys',
 'take',
 'take_along_axis',
 'tan',
 'tanh',
 'tensordot',
 'test',
 'testing',
 'tile',
 'timedelta64',
 'trace',
 'tracemalloc_domain',
 'transpose',
 'trapz',
 'tri',
 'tril',
 'tril_indices',
 'tril_indices_from',
 'trim_zeros',
 'triu',
 'triu_indices',
 'triu_indices_from',
 'true_divide',
 'trunc',
 'typecodes',
 'typename',
 'ubyte',
 'ufunc',
 'uint',
 'uint0',
 'uint16',
 'uint32',
 'uint64',
 'uint8',
 'uintc',
 'uintp',
 'ulonglong',
 'unicode_',
 'union1d',
 'unique',
 'unpackbits',
 'unravel_index',
 'unsignedinteger',
 'unwrap',
 'use_hugepage',
 'ushort',
 'vander',
 'var',
 'vdot',
 'vectorize',
 'version',
 'void',
 'void0',
 'vsplit',
 'vstack',
 'warnings',
 'where',
 'who',
 'zeros',
 'zeros_like']

In [ ]:
dir(pd)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_hashtable',
 '_is_numpy_dev',
 '_lib',
 '_libs',
 '_np_version_under1p18',
 '_testing',
 '_tslib',
 '_typing',
 '_version',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [ ]:
dir(sns)

['FacetGrid',
 'JointGrid',
 'PairGrid',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_core',
 '_decorators',
 '_docstrings',
 '_orig_rc_params',
 '_statistics',
 'algorithms',
 'axes_style',
 'axisgrid',
 'barplot',
 'blend_palette',
 'boxenplot',
 'boxplot',
 'categorical',
 'catplot',
 'choose_colorbrewer_palette',
 'choose_cubehelix_palette',
 'choose_dark_palette',
 'choose_diverging_palette',
 'choose_light_palette',
 'clustermap',
 'cm',
 'color_palette',
 'colors',
 'countplot',
 'crayon_palette',
 'crayons',
 'cubehelix_palette',
 'dark_palette',
 'desaturate',
 'despine',
 'displot',
 'distplot',
 'distributions',
 'diverging_palette',
 'dogplot',
 'ecdfplot',
 'external',
 'factorplot',
 'get_data_home',
 'get_dataset_names',
 'heatmap',
 'histplot',
 'hls_palette',
 'husl_palette',
 'jointplot',
 'kdeplot',
 'light_palette',
 'lineplot',
 'lmplot',
 'load_dataset',
 'matrix',
 'miscplot',
 'move_legend',
 'mpl',
 'mpl_palette',
 'pairplot',
 'palettes',
 'palplot',
 'plotting_context',
 'pointplot',
 'rcmod',
 'regplot',
 'regression',
 'relational',
 'relplot',
 'reset_defaults',
 'reset_orig',
 'residplot',
 'rugplot',
 'saturate',
 'scatterplot',
 'set',
 'set_color_codes',
 'set_context',
 'set_hls_values',
 'set_palette',
 'set_style',
 'set_theme',
 'stripplot',
 'swarmplot',
 'utils',
 'violinplot',
 'widgets',
 'xkcd_palette',
 'xkcd_rgb']

In [ ]:
dir(plt)

['Annotation',
 'Arrow',
 'Artist',
 'AutoLocator',
 'Axes',
 'Button',
 'Circle',
 'Figure',
 'FigureCanvasBase',
 'FixedFormatter',
 'FixedLocator',
 'FormatStrFormatter',
 'Formatter',
 'FuncFormatter',
 'GridSpec',
 'IndexLocator',
 'Line2D',
 'LinearLocator',
 'Locator',
 'LogFormatter',
 'LogFormatterExponent',
 'LogFormatterMathtext',
 'LogLocator',
 'MaxNLocator',
 'MultipleLocator',
 'Normalize',
 'NullFormatter',
 'NullLocator',
 'Number',
 'PolarAxes',
 'Polygon',
 'Rectangle',
 'ScalarFormatter',
 'Slider',
 'Subplot',
 'SubplotTool',
 'Text',
 'TickHelper',
 'Widget',
 '_INSTALL_FIG_OBSERVER',
 '_IP_REGISTERED',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_auto_draw_if_interactive',
 '_backend_mod',
 '_get_running_interactive_framework',
 '_interactive_bk',
 '_log',
 '_pylab_helpers',
 '_setp',
 '_setup_pyplot_info_docstrings',
 '_show',
 'acorr',
 'angle_spectrum',
 'annotate',
 'arrow',
 'autoscale',
 'autumn',
 'axes',
 'axhline',
 'axhspan',
 'axis',
 'axvline',
 'axvspan',
 'bar',
 'barbs',
 'barh',
 'bone',
 'box',
 'boxplot',
 'broken_barh',
 'cbook',
 'cla',
 'clabel',
 'clf',
 'clim',
 'close',
 'cm',
 'cohere',
 'colorbar',
 'colormaps',
 'connect',
 'contour',
 'contourf',
 'cool',
 'copper',
 'csd',
 'cycler',
 'dedent',
 'delaxes',
 'deprecated',
 'disconnect',
 'docstring',
 'draw',
 'draw_all',
 'draw_if_interactive',
 'errorbar',
 'eventplot',
 'figaspect',
 'figimage',
 'figlegend',
 'fignum_exists',
 'figtext',
 'figure',
 'fill',
 'fill_between',
 'fill_betweenx',
 'findobj',
 'flag',
 'functools',
 'gca',
 'gcf',
 'gci',
 'get',
 'get_backend',
 'get_cmap',
 'get_current_fig_manager',
 'get_figlabels',
 'get_fignums',
 'get_plot_commands',
 'get_scale_docs',
 'get_scale_names',
 'getp',
 'ginput',
 'gray',
 'grid',
 'hexbin',
 'hist',
 'hist2d',
 'hlines',
 'hot',
 'hsv',
 'importlib',
 'imread',
 'imsave',
 'imshow',
 'inferno',
 'inspect',
 'install_repl_displayhook',
 'interactive',
 'ioff',
 'ion',
 'isinteractive',
 'jet',
 'legend',
 'locator_params',
 'logging',
 'loglog',
 'magma',
 'magnitude_spectrum',
 'margins',
 'matplotlib',
 'matshow',
 'minorticks_off',
 'minorticks_on',
 'mlab',
 'new_figure_manager',
 'nipy_spectral',
 'np',
 'pause',
 'pcolor',
 'pcolormesh',
 'phase_spectrum',
 'pie',
 'pink',
 'plasma',
 'plot',
 'plot_date',
 'plotfile',
 'plotting',
 'polar',
 'prism',
 'psd',
 'quiver',
 'quiverkey',
 'rc',
 'rcParams',
 'rcParamsDefault',
 'rcParamsOrig',
 'rc_context',
 'rcdefaults',
 'rcsetup',
 're',
 'register_cmap',
 'rgrids',
 'savefig',
 'sca',
 'scatter',
 'sci',
 'semilogx',
 'semilogy',
 'set_cmap',
 'set_loglevel',
 'setp',
 'show',
 'silent_list',
 'specgram',
 'spring',
 'spy',
 'stackplot',
 'stem',
 'step',
 'streamplot',
 'style',
 'subplot',
 'subplot2grid',
 'subplot_tool',
 'subplots',
 'subplots_adjust',
 'summer',
 'suptitle',
 'switch_backend',
 'sys',
 'table',
 'text',
 'thetagrids',
 'tick_params',
 'ticklabel_format',
 'tight_layout',
 'time',
 'title',
 'tricontour',
 'tricontourf',
 'tripcolor',
 'triplot',
 'twinx',
 'twiny',
 'uninstall_repl_displayhook',
 'violinplot',
 'viridis',
 'vlines',
 'waitforbuttonpress',
 'warn_deprecated',
 'winter',
 'xcorr',
 'xkcd',
 'xlabel',
 'xlim',
 'xscale',
 'xticks',
 'ylabel',
 'ylim',
 'yscale',
 'yticks']

In [ ]:
help(unique)

Help on function unique in module pandas.core.algorithms:

unique(values)
    Hash table-based unique. Uniques are returned in order
    of appearance. This does NOT sort.

    Significantly faster than numpy.unique for long enough sequences.
    Includes NA values.

    Parameters
    ----------
    values : 1d array-like

    Returns
    -------
    numpy.ndarray or ExtensionArray

        The return can be:

        * Index : when the input is an Index
        * Categorical : when the input is a Categorical dtype
        * ndarray : when the input is a Series/ndarray

        Return numpy.ndarray or ExtensionArray.

    See Also
    --------
    Index.unique : Return unique values from an Index.
    Series.unique : Return unique values of Series object.

    Examples
    --------
    >>> pd.unique(pd.Series([2, 1, 3, 3]))
    array([2, 1, 3])

    >>> pd.unique(pd.Series([2] + [1] * 5))
    array([2, 1])

    >>> pd.unique(pd.Series([pd.Timestamp("20160101"), pd.Timestamp("20160101")]))
    array(['2016-01-01T00:00:00.000000000'], dtype='datetime64[ns]')

    >>> pd.unique(
    ...     pd.Series(
    ...         [
    ...             pd.Timestamp("20160101", tz="US/Eastern"),
    ...             pd.Timestamp("20160101", tz="US/Eastern"),
    ...         ]
    ...     )
    ... )
    <DatetimeArray>
    ['2016-01-01 00:00:00-05:00']
    Length: 1, dtype: datetime64[ns, US/Eastern]

    >>> pd.unique(
    ...     pd.Index(
    ...         [
    ...             pd.Timestamp("20160101", tz="US/Eastern"),
    ...             pd.Timestamp("20160101", tz="US/Eastern"),
    ...         ]
    ...     )
    ... )
    DatetimeIndex(['2016-01-01 00:00:00-05:00'],
            dtype='datetime64[ns, US/Eastern]',
            freq=None)

    >>> pd.unique(list("baabc"))
    array(['b', 'a', 'c'], dtype=object)

    An unordered Categorical will return categories in the
    order of appearance.

    >>> pd.unique(pd.Series(pd.Categorical(list("baabc"))))
    ['b', 'a', 'c']
    Categories (3, object): ['a', 'b', 'c']

    >>> pd.unique(pd.Series(pd.Categorical(list("baabc"), categories=list("abc"))))
    ['b', 'a', 'c']
    Categories (3, object): ['a', 'b', 'c']

    An ordered Categorical preserves the category ordering.

    >>> pd.unique(
    ...     pd.Series(
    ...         pd.Categorical(list("baabc"), categories=list("abc"), ordered=True)
    ...     )
    ... )
    ['b', 'a', 'c']
    Categories (3, object): ['a' < 'b' < 'c']

    An array of tuples

    >>> pd.unique([("a", "b"), ("b", "a"), ("a", "c"), ("b", "a")])
    array([('a', 'b'), ('b', 'a'), ('a', 'c')], dtype=object)

In [ ]:
#Soru 15:Lebron James için Atlanta (ATL) ve New York Knicks(NYK maçlarında),
#kaç şut atıp, kaç şut kaçırdığını gösteren bir dataframe oluşturun.
#Ve onu yazdırın.
dle = dfle  #Ayrı bir database oluşturulup gereksiz kolonlar çıkarıldı
dle = dle.drop('Unnamed: 0',axis = 1)
dle = dle.drop('self previous shot',axis = 1)
dle = dle.drop('player position',axis = 1)
dle = dle.drop('home game',axis = 1)
dle = dle.drop('location x',axis = 1)
dle = dle.drop('opponent previous shot',axis = 1)
dle = dle.drop('home team',axis = 1)
dle = dle.drop('shot type',axis = 1)
dle = dle.drop('away team',axis = 1)
dle = dle.drop('location y',axis = 1)
dle = dle.drop('time',axis = 1)
dle = dle.drop('date',axis = 1)
dle = dle.drop('time from last shot',axis = 1)
dle = dle.drop('quarter',axis = 1)
dle = dle.drop('points_gained',axis = 1)
dle = dle.drop('difference',axis = 1)
dle = dle.drop('points',axis = 1)

dle = dle.sort_values('HomeAway')#Sort edildi ve index düşürüldü
dle = dle.reset_index()
dle = dle.drop('index',axis = 1)

dATL = dle.iloc[0:48,:]
dNYK = dle.iloc[1035:1065,:]

a = dATL['current shot outcome'].value_counts()#Atalantaya atılan şutların sayısı
b = dNYK['current shot outcome'].value_counts()#New Yorka atılan şutların sayısı

data = [['ATL',a.SCORED,a.MISSED+a.BLOCKED],['NYK',b.SCORED,b.MISSED+b.BLOCKED]]
dfs = pd.DataFrame(data, columns = ['Team','Missed','Scored'])#İstenilen formata sokuldu
dfs

  Team  Missed  Scored
0  ATL      25      23
1  NYK      19      11

In [ ]:
#Soru 17:Cleveland'lı oyuncuları ve karşılarında oynadıkları takımları gruplayın.
#Her clevelandlı oyuncunun rakibe attığı toplam şutun miktarına göre büyükten küçüğe sıralayın.

dc = dk.sort_values('My_Team')#Veriler takımlar göre sort edildi.
dc = dc.reset_index()
dc = dc.drop('index',axis = 1)
dc = dc.iloc[0:6640,:]#Sadece Cleveland takımı veriden çekildi.

dc = dc.sort_values('shoot player')#Oyunculara göre tekrar sıralanıp.
dc = dc.reset_index()
dc = dc.drop('index',axis = 1)

for i in range(len(dc)):#Gereksiz string parçası çıkarıldı.
    dc['HomeAway'][i] = dc['HomeAway'][i].replace("_CLE","")
    dc['HomeAway'][i] = dc['HomeAway'][i].replace("CLE_","")

b = dc.groupby(['shoot player','HomeAway'])['Unnamed: 0'].count()#Sayılar bulunup.
b.sort_values(ascending = False)#Büyükten küçüğe sıradan yazdırıldı

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

shoot player     HomeAway
Kyrie Irving     ATL         91
LeBron James     CHA         84
                 BOS         83
                 ATL         80
Kyrie Irving     IND         79
                             ..
Jordan McRae     TOR          1
                 MIN          1
Chris Andersen   IND          1
James Jones      BOS          1
DeAndre Liggins  OKL          1
Name: Unnamed: 0, Length: 378, dtype: int64

In [ ]:
#Soru 18:Sütunların data type'leri eğer float'sa integer'a,
#integer ise float'a çevirin. (Orijinal data üstünde yapmayın). Yazdırın.

dfd = df.dropna()

dfd['Unnamed: 0'] = dfd['Unnamed: 0'].astype(float)
dfd['location x'] = dfd['location x'].astype(int)
dfd['points'] = dfd['points'].astype(float)
dfd['location y'] = dfd['location y'].astype(int)
dfd['time from last shot'] = dfd['time from last shot'].astype(int)
dfd['quarter'] = dfd['quarter'].astype(float)
dfd['points_gained'] = dfd['points_gained'].astype(int)
dfd['difference'] = dfd['difference'].astype(int)
dfd.dtypes

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

Unnamed: 0                float64
self previous shot         object
player position            object
home game                  object
location x                  int64
opponent previous shot     object
home team                  object
shot type                  object
points                    float64
away team                  object
location y                  int64
time                       object
date                       object
shoot player               object
time from last shot         int64
quarter                   float64
current shot outcome       object
My_Team                    object
HomeAway                   object
points_gained               int64
difference                  int64
Distance                  float64
Feature                    object
dtype: object

In [ ]:
dfd['Unnamed: 0'] = dfd['Unnamed: 0'].astype(int)
dfd['location x'] = dfd['location x'].astype(float)
dfd['points'] = dfd['points'].astype(int)
dfd['location y'] = dfd['location y'].astype(float)
dfd['time from last shot'] = dfd['time from last shot'].astype(float)
dfd['quarter'] = dfd['quarter'].astype(int)
dfd['points_gained'] = dfd['points_gained'].astype(float)
dfd['difference'] = dfd['difference'].astype(float)
dfd.dtypes

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

Unnamed: 0                  int64
self previous shot         object
player position            object
home game                  object
location x                float64
opponent previous shot     object
home team                  object
shot type                  object
points                      int64
away team                  object
location y                float64
time                       object
date                       object
shoot player               object
time from last shot       float64
quarter                     int64
current shot outcome       object
My_Team                    object
HomeAway                   object
points_gained             float64
difference                float64
Distance                  float64
Feature                    object
dtype: object

In [ ]:
#Soru 19: Self Previous Shot Sütununda boş veriler var mı?
#Bu boş veriler doldurulmalı mı? Eğer doldurulmalıysa, fillna() fonksiyonunu
#kullanarak doldurun.

dfq = df
na_sum = dfq['self previous shot'].isna().sum()
print("self previous shot kolonundaki nan değerlerin sayısı = ", na_sum)

#Boş veriler bulunmaktadır.Bu sutünün üzerinde işlem yapılacaksa ya doldurulmalı
#ya da drop edilmelidir bu değerler.

df['self previous shot'] = dfq['self previous shot'].fillna('MISSED')
na_sum = dfq['self previous shot'].isna().sum()
print("self previous shot kolonundaki nan değerlerin sayısı = ", na_sum)

self previous shot kolonundaki nan değerlerin sayısı =  156
self previous shot kolonundaki nan değerlerin sayısı =  0

In [ ]:
#Soru 20: Bütün sütun isimlerini internette sözlük kullanarak türkçeye çevirin,
#çevirdiğinizi gösterin.

dfn = df
dfn.columns

Index(['Unnamed: 0', 'self previous shot', 'player position', 'home game',
       'location x', 'opponent previous shot', 'home team', 'shot type',
       'points', 'away team', 'location y', 'time', 'date', 'shoot player',
       'time from last shot', 'quarter', 'current shot outcome', 'My_Team',
       'HomeAway', 'points_gained', 'difference', 'Distance', 'Feature'],
      dtype='object')

In [ ]:
dfn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13551 entries, 0 to 13550
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              13551 non-null  int64
 1   self previous shot      13551 non-null  object
 2   player position         13551 non-null  object
 3   home game               13551 non-null  object
 4   location x              13541 non-null  float64
 5   opponent previous shot  13452 non-null  object
 6   home team               13551 non-null  object
 7   shot type               13551 non-null  object
 8   points                  13551 non-null  int64
 9   away team               13551 non-null  object
 10  location y              13541 non-null  float64
 11  time                    13551 non-null  object
 12  date                    13551 non-null  object
 13  shoot player            13551 non-null  object
 14  time from last shot     12911 non-null  float64
 15  quarter                 13551 non-null  int64
 16  current shot outcome    13551 non-null  object
 17  My_Team                 13551 non-null  object
 18  HomeAway                13551 non-null  object
 19  points_gained           13551 non-null  float64
 20  difference              13551 non-null  float64
 21  Distance                13541 non-null  float64
 22  Feature                 13551 non-null  object
dtypes: float64(6), int64(3), object(14)
memory usage: 2.4+ MB

In [ ]:
dfn = dfn.rename(columns ={'Unnamed: 0':'İsimsiz: 0'})
dfn = dfn.rename(columns ={'self previous shot':'önceki atış'})
dfn = dfn.rename(columns ={'player position':'oyuncu pozisyonu'})
dfn = dfn.rename(columns ={'home game':'ev oyunu'})
dfn = dfn.rename(columns ={'location x':'lokasyon x'})
dfn = dfn.rename(columns ={'opponent previous shot':'rakip önceki atış'})
dfn = dfn.rename(columns ={'home team':'ev sahibi takım'})
dfn = dfn.rename(columns ={'shot type':'şut tipi'})
dfn = dfn.rename(columns ={'points':'puanlar'})
dfn = dfn.rename(columns ={'away team':'deplasman takımı'})
dfn = dfn.rename(columns ={'location y':'lokasyon y'})
dfn = dfn.rename(columns ={'time':'zaman'})
dfn = dfn.rename(columns ={'date':'tarih'})
dfn = dfn.rename(columns ={'shoot player':'şut oyuncusu'})
dfn = dfn.rename(columns ={'time from last shot':'son atıştan itibaren geçen süre'})
dfn = dfn.rename(columns ={'quarter':'çeyrek'})
dfn = dfn.rename(columns ={'current shot outcome':'mevcut atışın sonucu'})
dfn = dfn.rename(columns ={'My_Team':'Benim_takımım'})
dfn = dfn.rename(columns ={'HomeAway':'evdenuzak'})
dfn = dfn.rename(columns ={'points_gained':'kazanılan_puanlar'})
dfn = dfn.rename(columns ={'difference':'farklılık'})

dfn.columns

Index(['İsimsiz: 0', 'önceki atış', 'oyuncu pozisyonu', 'ev oyunu',
       'lokasyon x', 'rakip önceki atış', 'ev sahibi takım', 'şut tipi',
       'puanlar', 'deplasman takımı', 'lokasyon y', 'zaman', 'tarih',
       'şut oyuncusu', 'son atıştan itibaren geçen süre', 'çeyrek',
       'mevcut atışın sonucu', 'Benim_takımım', 'evdenuzak',
       'kazanılan_puanlar', 'farklılık', 'Distance', 'Feature'],
      dtype='object')

In [ ]:
dfn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13551 entries, 0 to 13550
Data columns (total 23 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   İsimsiz: 0                       13551 non-null  int64
 1   önceki atış                      13551 non-null  object
 2   oyuncu pozisyonu                 13551 non-null  object
 3   ev oyunu                         13551 non-null  object
 4   lokasyon x                       13541 non-null  float64
 5   rakip önceki atış                13452 non-null  object
 6   ev sahibi takım                  13551 non-null  object
 7   şut tipi                         13551 non-null  object
 8   puanlar                          13551 non-null  int64
 9   deplasman takımı                 13551 non-null  object
 10  lokasyon y                       13541 non-null  float64
 11  zaman                            13551 non-null  object
 12  tarih                            13551 non-null  object
 13  şut oyuncusu                     13551 non-null  object
 14  son atıştan itibaren geçen süre  12911 non-null  float64
 15  çeyrek                           13551 non-null  int64
 16  mevcut atışın sonucu             13551 non-null  object
 17  Benim_takımım                    13551 non-null  object
 18  evdenuzak                        13551 non-null  object
 19  kazanılan_puanlar                13551 non-null  float64
 20  farklılık                        13551 non-null  float64
 21  Distance                         13541 non-null  float64
 22  Feature                          13551 non-null  object
dtypes: float64(6), int64(3), object(14)
memory usage: 2.4+ MB

In [ ]:
#Soru 21: Elimizde ekstra maçlar olduğunu varsayalım. Hangi durumlarda concat,
#hangi durumlarda join kullanmamız gerektiğini düzgün bir şekilde açıklayın.

#join eklemek istediğimiz yeni verileri key değerleri ile eşleştirip belirli değerlere
#merge edebilirken, concat verileri düz bir şekilde sona ekler.Yani join bir merge
#fonksiyonu gibi çalışırken concate bir append fonksiyonu gibi çalışır.

Join eklemek istediğimiz yeni verileri key değerleri ile eşleştirip belirli değerlere merge edebilirken, concat verileri düz bir şekilde sona ekler.Yani join bir merge fonksiyonu gibi çalışırken concate bir append fonksiyonu gibi çalışır.

In [ ]:
#Bu kısımdan sonrası covide yakalanmam sebebiyle yazamadım hocam elimden geleni yaptığıma
#inanıyorum. Talihsizlik finalde
#umarım daha iyi iş çıkarırım.İyi bayramlar.